/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/usr/lib/nim/lib -I/home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751 -o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@mtest_dedupe.nim.c.o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@mtest_dedupe.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw;
typedef struct tySequence__focVCaRY1axNSYW9at2kyIQ tySequence__focVCaRY1axNSYW9at2kyIQ;
typedef struct tySequence__focVCaRY1axNSYW9at2kyIQ_Content tySequence__focVCaRY1axNSYW9at2kyIQ_Content;
typedef struct tySequence__jKinQKK5sMW4kMIzl4PsKQ tySequence__jKinQKK5sMW4kMIzl4PsKQ;
typedef struct tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content;
typedef struct tyTuple__yeSFujPok8SfAGi9apNECrw tyTuple__yeSFujPok8SfAGi9apNECrw;
typedef struct tySequence__0DSirJqYwP84JHfzAV1spQ tySequence__0DSirJqYwP84JHfzAV1spQ;
typedef struct tySequence__0DSirJqYwP84JHfzAV1spQ_Content tySequence__0DSirJqYwP84JHfzAV1spQ_Content;
typedef struct tyTuple__djYX1zUye8QMbG2U8KWWqg tyTuple__djYX1zUye8QMbG2U8KWWqg;
typedef struct tyObject_ExportedModule__aTfC2YZiDl69a8CTPw59cgiA tyObject_ExportedModule__aTfC2YZiDl69a8CTPw59cgiA;
typedef NU8 tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__focVCaRY1axNSYW9at2kyIQ {
  NI len; tySequence__focVCaRY1axNSYW9at2kyIQ_Content* p;
};
struct tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw {
	tySequence__focVCaRY1axNSYW9at2kyIQ data;
	NI counter;
	NI first;
	NI last;
};
struct tySequence__jKinQKK5sMW4kMIzl4PsKQ {
  NI len; tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content* p;
};
struct tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg {
	NIM_BOOL isUnquoted;
	tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A kind;
union{
	struct {
	NimStringV2 str;
} _kind_1;
	struct {
	NI64 num;
} _kind_2;
	struct {
	NF fnum;
} _kind_3;
	struct {
	NIM_BOOL bval;
} _kind_4;
	struct {
	tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw fields;
} _kind_6;
	struct {
	tySequence__jKinQKK5sMW4kMIzl4PsKQ elems;
} _kind_7;
};
};
typedef tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* tyArray__Upd0PWwyAjFVlIYNq7bTrQ[1];
struct tyTuple__yeSFujPok8SfAGi9apNECrw {
	NimStringV2 Field0;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* Field1;
};
typedef tyTuple__yeSFujPok8SfAGi9apNECrw tyArray__kmLHRhh084T9c6QHqkt8CmA[5];
typedef tyTuple__yeSFujPok8SfAGi9apNECrw tyArray__Plh5g9cJ2yX5eisHAioPIDg[4];
typedef NimStringV2 tyArray__YgExxhfgKcesA5EOUj1MOA[1];
struct tySequence__0DSirJqYwP84JHfzAV1spQ {
  NI len; tySequence__0DSirJqYwP84JHfzAV1spQ_Content* p;
};
struct tyTuple__djYX1zUye8QMbG2U8KWWqg {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* Field3;
};
struct tySequence__focVCaRY1axNSYW9at2kyIQ_Content { NI cap; tyTuple__djYX1zUye8QMbG2U8KWWqg data[SEQ_DECL_SIZE]; };
struct tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content { NI cap; tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* data[SEQ_DECL_SIZE]; };
struct tyObject_ExportedModule__aTfC2YZiDl69a8CTPw59cgiA {
	NimStringV2 name;
	void* initAddr2;
	void* initAddr3;
};
struct tySequence__0DSirJqYwP84JHfzAV1spQ_Content { NI cap; tyObject_ExportedModule__aTfC2YZiDl69a8CTPw59cgiA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, percent___OOZOOZsrcZglaucoplastic_u252)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** elements_p0, NI elements_p0Len_0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, percent___pureZjson_u2195)(tyTuple__yeSFujPok8SfAGi9apNECrw* keyVals_p0, NI keyVals_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, percent___pureZjson_u2166)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u321)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, plasticAssistantNormalizeLearningCandidate__OOZOOZsrcZglaucoplastic_u4518)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* existingThings_p0, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* candidate_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnimpyZpy95lib_u1719)(tySequence__0DSirJqYwP84JHfzAV1spQ dest_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpnimpyatspy_libdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atprandomdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_2 = { 4 | NIM_STRLIT_FLAG, "kind" };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_3 = {4, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_2};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_4 = { 6 | NIM_STRLIT_FLAG, "person" };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_5 = {6, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_4};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_6 = { 5 | NIM_STRLIT_FLAG, "title" };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_7 = {5, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_6};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_8 = { 16 | NIM_STRLIT_FLAG, "Nome do Usu\303\241rio" };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_9 = {16, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_8};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_10 = { 7 | NIM_STRLIT_FLAG, "content" };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_11 = {7, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_10};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_12 = { 25 | NIM_STRLIT_FLAG, "\303\215caro Glauco de Oliveira" };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_13 = {25, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_12};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_14 = { 5 | NIM_STRLIT_FLAG, "scope" };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_15 = {5, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_14};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_16 = { 6 | NIM_STRLIT_FLAG, "global" };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_17 = {6, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_16};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_18 = { 6 | NIM_STRLIT_FLAG, "status" };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_19 = {6, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_18};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_20 = { 6 | NIM_STRLIT_FLAG, "active" };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_21 = {6, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_20};
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_22 = {4, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_2};
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_23 = {6, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_4};
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_24 = {5, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_6};
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_25 = {25, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_12};
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_26 = {7, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_10};
static const struct {
  NI cap; NIM_CHAR data[44+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_27 = { 44 | NIM_STRLIT_FLAG, "Nome do usu\303\241rio: \303\215caro Glauco de Oliveira." };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_28 = {44, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_27};
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_29 = {5, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_14};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_30 = { 20 | NIM_STRLIT_FLAG, "session:session-test" };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_31 = {20, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_30};
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_32 = {4, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_2};
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_33 = {6, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_4};
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_34 = {5, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_6};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_35 = { 15 | NIM_STRLIT_FLAG, "Identifica\303\247\303\243o" };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_36 = {15, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_35};
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_37 = {7, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_10};
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_38 = { 33 | NIM_STRLIT_FLAG, "Usu\303\241rio identificado na sess\303\243o." };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_39 = {33, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_38};
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_40 = {5, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_14};
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_41 = {20, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_30};
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_42 = {4, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_2};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_43 = { 10 | NIM_STRLIT_FLAG, "preference" };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_44 = {10, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_43};
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_45 = {5, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_6};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_46 = { 18 | NIM_STRLIT_FLAG, "Estilo de Resposta" };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_47 = {18, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_46};
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_48 = {7, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_10};
static const struct {
  NI cap; NIM_CHAR data[46+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_49 = { 46 | NIM_STRLIT_FLAG, "O usu\303\241rio prefere respostas curtas e diretas." };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_50 = {46, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_49};
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_51 = {5, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_14};
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_52 = {6, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_16};
static const struct {
  NI cap; NIM_CHAR data[199+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_53 = { 199 | NIM_STRLIT_FLAG, "/home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/test_dedupe.nim(35, 9) `plasticAssistantNormalizeLearningCandidate(existing, duplicateByAnswer).kind ==\012    JNull` " };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_54 = {199, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_53};
static const struct {
  NI cap; NIM_CHAR data[190+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_55 = { 190 | NIM_STRLIT_FLAG, "/home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/test_dedupe.nim(42, 9) `plasticAssistantNormalizeLearningCandidate(existing, sessionNoise).kind == JNull` " };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_56 = {190, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_55};
static const struct {
  NI cap; NIM_CHAR data[199+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_57 = { 199 | NIM_STRLIT_FLAG, "/home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/test_dedupe.nim(49, 9) `plasticAssistantNormalizeLearningCandidate(existing, validPreference).kind ==\012    JObject` " };
static const NimStringV2 TM__lVyOhOfMhXNxdV9cQY9aMlMw_58 = {199, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_57};
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__lVyOhOfMhXNxdV9cQY9aMlMw_60 = { 26 | NIM_STRLIT_FLAG, "filtro de redund\303\242ncia: OK" };
static NIM_CONST tyArray__YgExxhfgKcesA5EOUj1MOA TM__lVyOhOfMhXNxdV9cQY9aMlMw_59 = {{26, (NimStrPayload*)&TM__lVyOhOfMhXNxdV9cQY9aMlMw_60}}
;
N_LIB_PRIVATE tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* existing__test95dedupe_u38;
N_LIB_PRIVATE tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* duplicateByAnswer__test95dedupe_u55;
N_LIB_PRIVATE tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* sessionNoise__test95dedupe_u72;
N_LIB_PRIVATE tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* validPreference__test95dedupe_u89;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
extern tySequence__0DSirJqYwP84JHfzAV1spQ exportedModules__pkgZnimpyZpy95lib_u289;
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}

N_LIB_PRIVATE void PreMainInner(void) {
	atpnimpyatspy_libdotnim_Init000();
	atprandomdotnim_Init000();
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atpsystemdotnim_Init000();
	(*inner)();
#else
	atpsystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD_;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__2;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__3;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__4;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__5;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__6;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__7;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__8;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__9;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__10;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__11;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__12;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__13;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__14;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__15;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__16;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__17;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__18;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__19;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__20;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__21;
	tyArray__Upd0PWwyAjFVlIYNq7bTrQ T2_;
	tyArray__kmLHRhh084T9c6QHqkt8CmA T3_;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T4_;
	tyArray__Plh5g9cJ2yX5eisHAioPIDg T5_;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T6_;
	tyArray__Plh5g9cJ2yX5eisHAioPIDg T7_;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T8_;
	tyArray__Plh5g9cJ2yX5eisHAioPIDg T9_;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T10_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("test_dedupe", "/home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/test_dedupe.nim");
nimErr_ = nimErrorFlag();
	colontmpD_ = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	colontmpD__3 = NIM_NIL;
	colontmpD__4 = NIM_NIL;
	colontmpD__5 = NIM_NIL;
	colontmpD__6 = NIM_NIL;
	colontmpD__7 = NIM_NIL;
	colontmpD__8 = NIM_NIL;
	colontmpD__9 = NIM_NIL;
	colontmpD__10 = NIM_NIL;
	colontmpD__11 = NIM_NIL;
	colontmpD__12 = NIM_NIL;
	colontmpD__13 = NIM_NIL;
	colontmpD__14 = NIM_NIL;
	colontmpD__15 = NIM_NIL;
	colontmpD__16 = NIM_NIL;
	colontmpD__17 = NIM_NIL;
	colontmpD__18 = NIM_NIL;
	colontmpD__19 = NIM_NIL;
	colontmpD__20 = NIM_NIL;
	colontmpD__21 = NIM_NIL;
	nimlf_(4, "/home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/test_dedupe.nim");	nimZeroMem((void*)T2_, sizeof(tyArray__Upd0PWwyAjFVlIYNq7bTrQ));
	nimln_(10);	nimZeroMem((void*)T3_, sizeof(tyArray__kmLHRhh084T9c6QHqkt8CmA));
	T3_[0].Field0 = TM__lVyOhOfMhXNxdV9cQY9aMlMw_3;
	nimln_(6);	colontmpD_ = percent___pureZjson_u2166(TM__lVyOhOfMhXNxdV9cQY9aMlMw_5);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_[0].Field1 = colontmpD_;
	T3_[1].Field0 = TM__lVyOhOfMhXNxdV9cQY9aMlMw_7;
	nimln_(7);	colontmpD__2 = percent___pureZjson_u2166(TM__lVyOhOfMhXNxdV9cQY9aMlMw_9);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_[1].Field1 = colontmpD__2;
	T3_[2].Field0 = TM__lVyOhOfMhXNxdV9cQY9aMlMw_11;
	nimln_(8);	colontmpD__3 = percent___pureZjson_u2166(TM__lVyOhOfMhXNxdV9cQY9aMlMw_13);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_[2].Field1 = colontmpD__3;
	T3_[3].Field0 = TM__lVyOhOfMhXNxdV9cQY9aMlMw_15;
	nimln_(9);	colontmpD__4 = percent___pureZjson_u2166(TM__lVyOhOfMhXNxdV9cQY9aMlMw_17);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_[3].Field1 = colontmpD__4;
	T3_[4].Field0 = TM__lVyOhOfMhXNxdV9cQY9aMlMw_19;
	nimln_(10);	colontmpD__5 = percent___pureZjson_u2166(TM__lVyOhOfMhXNxdV9cQY9aMlMw_21);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_[4].Field1 = colontmpD__5;
	colontmpD__6 = percent___pureZjson_u2195(T3_, 5);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[0] = colontmpD__6;
	nimln_(4);	T4_ = NIM_NIL;
	T4_ = percent___OOZOOZsrcZglaucoplastic_u252(T2_, 1);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u321(T4_); goto LA1_;}
	existing__test95dedupe_u38 = T4_;
	nimln_(14);	nimZeroMem((void*)T5_, sizeof(tyArray__Plh5g9cJ2yX5eisHAioPIDg));
	T5_[0].Field0 = TM__lVyOhOfMhXNxdV9cQY9aMlMw_22;
	nimln_(15);	colontmpD__7 = percent___pureZjson_u2166(TM__lVyOhOfMhXNxdV9cQY9aMlMw_23);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T5_[0].Field1 = colontmpD__7;
	T5_[1].Field0 = TM__lVyOhOfMhXNxdV9cQY9aMlMw_24;
	nimln_(16);	colontmpD__8 = percent___pureZjson_u2166(TM__lVyOhOfMhXNxdV9cQY9aMlMw_25);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T5_[1].Field1 = colontmpD__8;
	T5_[2].Field0 = TM__lVyOhOfMhXNxdV9cQY9aMlMw_26;
	nimln_(17);	colontmpD__9 = percent___pureZjson_u2166(TM__lVyOhOfMhXNxdV9cQY9aMlMw_28);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T5_[2].Field1 = colontmpD__9;
	T5_[3].Field0 = TM__lVyOhOfMhXNxdV9cQY9aMlMw_29;
	nimln_(18);	colontmpD__10 = percent___pureZjson_u2166(TM__lVyOhOfMhXNxdV9cQY9aMlMw_31);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T5_[3].Field1 = colontmpD__10;
	nimln_(14);	T6_ = NIM_NIL;
	T6_ = percent___pureZjson_u2195(T5_, 4);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u321(T6_); goto LA1_;}
	duplicateByAnswer__test95dedupe_u55 = T6_;
	nimln_(21);	nimZeroMem((void*)T7_, sizeof(tyArray__Plh5g9cJ2yX5eisHAioPIDg));
	T7_[0].Field0 = TM__lVyOhOfMhXNxdV9cQY9aMlMw_32;
	nimln_(22);	colontmpD__11 = percent___pureZjson_u2166(TM__lVyOhOfMhXNxdV9cQY9aMlMw_33);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T7_[0].Field1 = colontmpD__11;
	T7_[1].Field0 = TM__lVyOhOfMhXNxdV9cQY9aMlMw_34;
	nimln_(23);	colontmpD__12 = percent___pureZjson_u2166(TM__lVyOhOfMhXNxdV9cQY9aMlMw_36);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T7_[1].Field1 = colontmpD__12;
	T7_[2].Field0 = TM__lVyOhOfMhXNxdV9cQY9aMlMw_37;
	nimln_(24);	colontmpD__13 = percent___pureZjson_u2166(TM__lVyOhOfMhXNxdV9cQY9aMlMw_39);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T7_[2].Field1 = colontmpD__13;
	T7_[3].Field0 = TM__lVyOhOfMhXNxdV9cQY9aMlMw_40;
	nimln_(25);	colontmpD__14 = percent___pureZjson_u2166(TM__lVyOhOfMhXNxdV9cQY9aMlMw_41);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T7_[3].Field1 = colontmpD__14;
	nimln_(21);	T8_ = NIM_NIL;
	T8_ = percent___pureZjson_u2195(T7_, 4);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u321(T8_); goto LA1_;}
	sessionNoise__test95dedupe_u72 = T8_;
	nimln_(28);	nimZeroMem((void*)T9_, sizeof(tyArray__Plh5g9cJ2yX5eisHAioPIDg));
	T9_[0].Field0 = TM__lVyOhOfMhXNxdV9cQY9aMlMw_42;
	nimln_(29);	colontmpD__15 = percent___pureZjson_u2166(TM__lVyOhOfMhXNxdV9cQY9aMlMw_44);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T9_[0].Field1 = colontmpD__15;
	T9_[1].Field0 = TM__lVyOhOfMhXNxdV9cQY9aMlMw_45;
	nimln_(30);	colontmpD__16 = percent___pureZjson_u2166(TM__lVyOhOfMhXNxdV9cQY9aMlMw_47);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T9_[1].Field1 = colontmpD__16;
	T9_[2].Field0 = TM__lVyOhOfMhXNxdV9cQY9aMlMw_48;
	nimln_(31);	colontmpD__17 = percent___pureZjson_u2166(TM__lVyOhOfMhXNxdV9cQY9aMlMw_50);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T9_[2].Field1 = colontmpD__17;
	T9_[3].Field0 = TM__lVyOhOfMhXNxdV9cQY9aMlMw_51;
	nimln_(32);	colontmpD__18 = percent___pureZjson_u2166(TM__lVyOhOfMhXNxdV9cQY9aMlMw_52);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T9_[3].Field1 = colontmpD__18;
	nimln_(28);	T10_ = NIM_NIL;
	T10_ = percent___pureZjson_u2195(T9_, 4);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u321(T10_); goto LA1_;}
	validPreference__test95dedupe_u89 = T10_;
	nimln_(35);	{
		colontmpD__19 = plasticAssistantNormalizeLearningCandidate__OOZOOZsrcZglaucoplastic_u4518(existing__test95dedupe_u38, duplicateByAnswer__test95dedupe_u55);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!!(((*colontmpD__19).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)0)))) goto LA13_;
		failedAssertImpl__stdZassertions_u95(TM__lVyOhOfMhXNxdV9cQY9aMlMw_54);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA13_: ;
	nimln_(42);	{
		colontmpD__20 = plasticAssistantNormalizeLearningCandidate__OOZOOZsrcZglaucoplastic_u4518(existing__test95dedupe_u38, sessionNoise__test95dedupe_u72);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!!(((*colontmpD__20).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)0)))) goto LA17_;
		failedAssertImpl__stdZassertions_u95(TM__lVyOhOfMhXNxdV9cQY9aMlMw_56);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA17_: ;
	nimln_(49);	{
		colontmpD__21 = plasticAssistantNormalizeLearningCandidate__OOZOOZsrcZglaucoplastic_u4518(existing__test95dedupe_u38, validPreference__test95dedupe_u89);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!!(((*colontmpD__21).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)5)))) goto LA21_;
		failedAssertImpl__stdZassertions_u95(TM__lVyOhOfMhXNxdV9cQY9aMlMw_58);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA21_: ;
	nimln_(56);	echoBinSafe(TM__lVyOhOfMhXNxdV9cQY9aMlMw_59, 1);
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimlf_(934, "/usr/lib/nim/lib/system.nim");		eqdestroy___pureZjson_u321(colontmpD__21);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__20);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__19);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__18);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__17);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__16);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__15);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__14);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__13);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__12);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__11);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__10);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__9);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__8);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__7);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__6);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__5);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__4);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___pureZjson_u321(validPreference__test95dedupe_u89);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___pureZjson_u321(sessionNoise__test95dedupe_u72);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___pureZjson_u321(duplicateByAnswer__test95dedupe_u55);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___pureZjson_u321(existing__test95dedupe_u38);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(436, "/home/icarogdo/.nimble/pkgs2/nimpy-0.2.1-22173fb24ce9ca9d1c1db63fe15bdfb14e69c76a/nimpy/py_lib.nim");	eqdestroy___pkgZnimpyZpy95lib_u1719(exportedModules__pkgZnimpyZpy95lib_u289);
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

