/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/usr/lib/nim/lib -I/home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751 -o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@pglaucoplastic.nim.c.o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@pglaucoplastic.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw;
typedef struct tySequence__focVCaRY1axNSYW9at2kyIQ tySequence__focVCaRY1axNSYW9at2kyIQ;
typedef struct tySequence__focVCaRY1axNSYW9at2kyIQ_Content tySequence__focVCaRY1axNSYW9at2kyIQ_Content;
typedef struct tySequence__jKinQKK5sMW4kMIzl4PsKQ tySequence__jKinQKK5sMW4kMIzl4PsKQ;
typedef struct tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyTuple__djYX1zUye8QMbG2U8KWWqg tyTuple__djYX1zUye8QMbG2U8KWWqg;
typedef N_CDECL_PTR(int, tyProc__OMdFHeVk9cEJv70imKPcZFA) (void);
typedef N_CDECL_PTR(void, tyProc__2qBhEXbLxiRYO7R7Cyo2TA) (int state_p0);
typedef N_CDECL_PTR(void*, tyProc__NzboHqZVJcbdtVGYrOosXQ) (void);
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A;
struct tySequence__focVCaRY1axNSYW9at2kyIQ {
  NI len; tySequence__focVCaRY1axNSYW9at2kyIQ_Content* p;
};
struct tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw {
	tySequence__focVCaRY1axNSYW9at2kyIQ data;
	NI counter;
	NI first;
	NI last;
};
struct tySequence__jKinQKK5sMW4kMIzl4PsKQ {
  NI len; tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content* p;
};
struct tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg {
	NIM_BOOL isUnquoted;
	tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A kind;
union{
	struct {
	NimStringV2 str;
} _kind_1;
	struct {
	NI64 num;
} _kind_2;
	struct {
	NF fnum;
} _kind_3;
	struct {
	NIM_BOOL bval;
} _kind_4;
	struct {
	tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw fields;
} _kind_6;
	struct {
	tySequence__jKinQKK5sMW4kMIzl4PsKQ elems;
} _kind_7;
};
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef NimStringV2 tyArray__Seu7uK9aaOSN0BK3EAjjSHw[4];
typedef NimStringV2 tyArray__wgmwCG2MY84OFtPmYaVG9bA[14];
struct tyTuple__djYX1zUye8QMbG2U8KWWqg {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* Field3;
};
struct tySequence__focVCaRY1axNSYW9at2kyIQ_Content { NI cap; tyTuple__djYX1zUye8QMbG2U8KWWqg data[SEQ_DECL_SIZE]; };
struct tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content { NI cap; tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJNull__pureZjson_u438)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u321)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZjson_u3707)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* node_p0, NimStringV2 key_p1);
static N_INLINE(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, X5BX5D___pureZjson_u3594)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* node_p0, NimStringV2 name_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u324)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** dest_p0, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg**, X5BX5D___pureZjson_u3102)(tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw* t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZjson_u20)(tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A e_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldErrorStr)(NimStringV2 f_p0, NimStringV2 discVal_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuStrip)(NimStringV2 s_p0, NIM_BOOL leading_p1, NIM_BOOL trailing_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getStr__pureZjson_u551)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* n_p0, NimStringV2 default_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, plasticAssistantIsNameLearningCandidate__OOZOOZsrcZglaucoplastic_u4293)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* candidate_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, plasticAssistantLearningKey__OOZOOZsrcZglaucoplastic_u4290)(NimStringV2 value_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuJoinSep)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 sep_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitWhitespace)(NimStringV2 s_p0, NI maxsplit_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToLowerAsciiStr)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5657)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
static N_INLINE(NIM_BOOL, contains__stdZenumutils_u50)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1);
static N_INLINE(NI, find__stdZenumutils_u55)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringV2 s_p0, NimStringV2 prefix_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, plasticAssistantIsLearningNoise__OOZOOZsrcZglaucoplastic_u4363)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* candidate_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_u1900)(NimStringV2 s_p0, NimStringV2 sub_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u257)(tySequence__jKinQKK5sMW4kMIzl4PsKQ* dest_p0, tySequence__jKinQKK5sMW4kMIzl4PsKQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u254)(tySequence__jKinQKK5sMW4kMIzl4PsKQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, copy__pureZjson_u4783)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* p_p0);
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_2 = { 5 | NIM_STRLIT_FLAG, "title" };
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_3 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_2};
static const struct {
  NI cap; NIM_CHAR data[57+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_4 = { 57 | NIM_STRLIT_FLAG, "/usr/lib/nim/lib/pure/json.nim(521, 9) `not isNil(node)` " };
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_5 = {57, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_4};
static const struct {
  NI cap; NIM_CHAR data[62+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_6 = { 62 | NIM_STRLIT_FLAG, "/usr/lib/nim/lib/pure/json.nim(522, 9) `node.kind == JObject` " };
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_7 = {62, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_6};
static const struct {
  NI cap; NIM_CHAR data[70+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_8 = { 70 | NIM_STRLIT_FLAG, "field \'fields\' is not accessible for type \'JsonNodeObj\' using \'kind = " };
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_9 = {70, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_8};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_10 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_2};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_11 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_2};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_12 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_13 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__HInI9a49a9a9bwob72ueo9cK5xA_14 = {
0x00, 0x3e, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_15 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_16 = { 7 | NIM_STRLIT_FLAG, "content" };
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_17 = {7, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_16};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_18 = {7, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_16};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_19 = {7, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_16};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_20 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_21 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_22 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_2};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_23 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_2};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_24 = { 1 | NIM_STRLIT_FLAG, " " };
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_25 = {1, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_24};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_26 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_2};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_27 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_28 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_29 = {7, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_16};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_30 = {7, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_16};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_31 = {7, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_16};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_32 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_33 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_36 = { 16 | NIM_STRLIT_FLAG, "nome do usu\303\241rio" };
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_37 = { 15 | NIM_STRLIT_FLAG, "nome do usuario" };
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_38 = { 25 | NIM_STRLIT_FLAG, "nome completo do usu\303\241rio" };
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_39 = { 24 | NIM_STRLIT_FLAG, "nome completo do usuario" };
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_40 = { 17 | NIM_STRLIT_FLAG, "nome do usu\303\241rio:" };
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_41 = {17, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_40};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_42 = { 16 | NIM_STRLIT_FLAG, "nome do usuario:" };
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_43 = {16, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_42};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_44 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_2};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_45 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_2};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_46 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_2};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_47 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_48 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_49 = {7, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_16};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_50 = {7, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_16};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_51 = {7, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_16};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_52 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_53 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_54 = {1, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_24};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_56 = { 20 | NIM_STRLIT_FLAG, "o usu\303\241rio perguntou" };
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_57 = { 19 | NIM_STRLIT_FLAG, "o usuario perguntou" };
static const struct {
  NI cap; NIM_CHAR data[32+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_58 = { 32 | NIM_STRLIT_FLAG, "usu\303\241rio identificado na sess\303\243o" };
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_59 = { 30 | NIM_STRLIT_FLAG, "usuario identificado na sessao" };
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_60 = { 22 | NIM_STRLIT_FLAG, "usu\303\241rio se apresentou" };
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_61 = { 21 | NIM_STRLIT_FLAG, "usuario se apresentou" };
static const struct {
  NI cap; NIM_CHAR data[31+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_62 = { 31 | NIM_STRLIT_FLAG, "o assistente n\303\243o possui acesso" };
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_63 = { 30 | NIM_STRLIT_FLAG, "o assistente nao possui acesso" };
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_64 = { 26 | NIM_STRLIT_FLAG, "o assistente n\303\243o armazena" };
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_65 = { 25 | NIM_STRLIT_FLAG, "o assistente nao armazena" };
static const struct {
  NI cap; NIM_CHAR data[29+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_66 = { 29 | NIM_STRLIT_FLAG, "nenhuma informa\303\247\303\243o dur\303\241vel" };
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_67 = { 26 | NIM_STRLIT_FLAG, "nenhuma informacao duravel" };
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_68 = { 18 | NIM_STRLIT_FLAG, "in\303\255cio de sess\303\243o" };
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_69 = { 16 | NIM_STRLIT_FLAG, "inicio de sessao" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_70 = { 5 | NIM_STRLIT_FLAG, "scope" };
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_71 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_70};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_72 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_70};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_73 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_70};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_74 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_75 = { 6 | NIM_STRLIT_FLAG, "global" };
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_76 = {6, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_75};
static const struct {
  NI cap; NIM_CHAR data[106+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_77 = { 106 | NIM_STRLIT_FLAG, "/usr/lib/nim/lib/pure/json.nim(834, 3) `node.kind == JArray` : items() can not iterate a JsonNode of kind " };
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_78 = {106, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_77};
static const struct {
  NI cap; NIM_CHAR data[69+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_79 = { 69 | NIM_STRLIT_FLAG, "field \'elems\' is not accessible for type \'JsonNodeObj\' using \'kind = " };
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_80 = {69, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_79};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_81 = { 6 | NIM_STRLIT_FLAG, "status" };
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_82 = {6, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_81};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_83 = {6, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_81};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_84 = {6, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_81};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_85 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_86 = { 9 | NIM_STRLIT_FLAG, "forgotten" };
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_87 = {9, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_86};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_88 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_2};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_89 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_2};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_90 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_2};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_91 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_92 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_93 = {7, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_16};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_94 = {7, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_16};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_95 = {7, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_16};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_96 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_97 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_98 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_70};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_99 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_70};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_100 = {5, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_70};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_101 = {0, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_12};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_102 = {6, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_75};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_103 = { 8 | NIM_STRLIT_FLAG, "session:" };
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_104 = {8, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_103};
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_105 = {6, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_75};
static const struct {
  NI cap; NIM_CHAR data[114+1];
} TM__HInI9a49a9a9bwob72ueo9cK5xA_106 = { 114 | NIM_STRLIT_FLAG, "/usr/lib/nim/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__HInI9a49a9a9bwob72ueo9cK5xA_107 = {114, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_106};
static NIM_CONST tyArray__Seu7uK9aaOSN0BK3EAjjSHw TM__HInI9a49a9a9bwob72ueo9cK5xA_35 = {{16, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_36},
{15, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_37},
{25, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_38},
{24, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_39}}
;
static NIM_CONST tyArray__wgmwCG2MY84OFtPmYaVG9bA TM__HInI9a49a9a9bwob72ueo9cK5xA_55 = {{20, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_56},
{19, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_57},
{32, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_58},
{30, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_59},
{22, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_60},
{21, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_61},
{31, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_62},
{30, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_63},
{26, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_64},
{25, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_65},
{29, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_66},
{26, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_67},
{18, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_68},
{16, (NimStrPayload*)&TM__HInI9a49a9a9bwob72ueo9cK5xA_69}}
;
N_LIB_PRIVATE void* plasticPythonLibraryHandle__OOZOOZsrcZglaucoplastic_u16;
N_LIB_PRIVATE tyProc__OMdFHeVk9cEJv70imKPcZFA plasticPyGILEnsureProc__OOZOOZsrcZglaucoplastic_u17;
N_LIB_PRIVATE tyProc__2qBhEXbLxiRYO7R7Cyo2TA plasticPyGILReleaseProc__OOZOOZsrcZglaucoplastic_u18;
N_LIB_PRIVATE tyProc__NzboHqZVJcbdtVGYrOosXQ plasticPyEvalSaveThreadProc__OOZOOZsrcZglaucoplastic_u19;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
static N_INLINE(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, X5BX5D___pureZjson_u3594)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* node_p0, NimStringV2 name_p1) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** T9_;
NIM_BOOL* nimErr_;
	nimfr_("[]", "/usr/lib/nim/lib/pure/json.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimlf_(521, "/usr/lib/nim/lib/pure/json.nim");	{
		if (!!(!((node_p0 == 0)))) goto LA3_;
		failedAssertImpl__stdZassertions_u95(TM__HInI9a49a9a9bwob72ueo9cK5xA_5);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimln_(522);	{
		if (!!(((*node_p0).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)5)))) goto LA7_;
		failedAssertImpl__stdZassertions_u95(TM__HInI9a49a9a9bwob72ueo9cK5xA_7);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA7_: ;
	nimlf_(934, "/usr/lib/nim/lib/system.nim");	nimlf_(525, "/usr/lib/nim/lib/pure/json.nim");	if (!(((32 &((NU8)1<<((NU)(((*node_p0).kind))&7U)))!=0))) 	{ raiseFieldErrorStr(TM__HInI9a49a9a9bwob72ueo9cK5xA_9, dollar___pureZjson_u20((*node_p0).kind)); goto BeforeRet_;
	}
	T9_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg**)0;
	T9_ = X5BX5D___pureZjson_u3102((&(*node_p0)._kind_6.fields), name_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(934, "/usr/lib/nim/lib/system.nim");	eqcopy___pureZjson_u324(&result, (*T9_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, plasticAssistantLearningKey__OOZOOZsrcZglaucoplastic_u4290)(NimStringV2 value_p0) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ colontmpD__2;
NIM_BOOL* nimErr_;
	nimfr_("plasticAssistantLearningKey", "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimlf_(1373, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");	colontmpD_ = nsuToLowerAsciiStr(value_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	colontmpD__2 = nsuSplitWhitespace(colontmpD_, ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = nsuJoinSep(((colontmpD__2).p) ? (colontmpD__2.p->data) : NIM_NIL, colontmpD__2.len, TM__HInI9a49a9a9bwob72ueo9cK5xA_25);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(2219, "/usr/lib/nim/lib/system.nim");	eqdestroy___system_u5657(colontmpD__2);
	nimln_(394);	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "/usr/lib/nim/lib/system/strmantle.nim");
{	nimlf_(33, "/usr/lib/nim/lib/system/strmantle.nim");	result = NIM_FALSE;
	nimln_(34);	alen_1 = a_p0.len;
	nimln_(35);	blen_1 = b_p1.len;
	nimln_(36);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(37);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(32);			nimln_(37);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(38);		nimln_(32);		nimln_(38);		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, find__stdZenumutils_u55)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1) {
	NI result;
	nimfr_("find", "/usr/lib/nim/lib/system.nim");
{	nimlf_(1918, "/usr/lib/nim/lib/system.nim");	result = ((NI)0);
	{
		NimStringV2* i_1;
		NI i_2;
		i_1 = (NimStringV2*)0;
		nimlf_(18, "/usr/lib/nim/lib/system/iterators.nim");		i_2 = ((NI)0);
		{
			nimln_(19);			while (1) {
				NI TM__HInI9a49a9a9bwob72ueo9cK5xA_34;
				if (!(i_2 < a_p0Len_0)) goto LA3;
				nimlf_(1919, "/usr/lib/nim/lib/system.nim");				if (i_2 < 0 || i_2 >= a_p0Len_0){ raiseIndexError2(i_2,a_p0Len_0-1); goto BeforeRet_;
				}
				i_1 = (&a_p0[i_2]);
				nimln_(1920);				{
					if (!eqStrings((*i_1), item_p1)) goto LA6_;
					goto BeforeRet_;
				}
LA6_: ;
				nimln_(1921);				if (nimAddInt(result, ((NI)1), &TM__HInI9a49a9a9bwob72ueo9cK5xA_34)) { raiseOverflow(); goto BeforeRet_;
				};
				result = (NI)(TM__HInI9a49a9a9bwob72ueo9cK5xA_34);
				nimlf_(13, "/usr/lib/nim/lib/system/iterators.nim");				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	nimlf_(1922, "/usr/lib/nim/lib/system.nim");	result = ((NI)-1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, contains__stdZenumutils_u50)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "/usr/lib/nim/lib/system.nim");
{	nimln_(1936);	nimln_(1924);	nimln_(1936);	T1_ = (NI)0;
	T1_ = find__stdZenumutils_u55(a_p0, a_p0Len_0, item_p1);
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, plasticAssistantIsNameLearningCandidate__OOZOOZsrcZglaucoplastic_u4293)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* candidate_p0) {
	NIM_BOOL result;
	NimStringV2 title_1;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD_;
	NimStringV2 content_1;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__2;
	NimStringV2 T6_;
NIM_BOOL oldNimErrFin13_;
	NimStringV2 T17_;
NIM_BOOL oldNimErrFin24_;
	NIM_BOOL T28_;
	NIM_BOOL T29_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("plasticAssistantIsNameLearningCandidate", "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	title_1.len = 0; title_1.p = NIM_NIL;
	colontmpD_ = NIM_NIL;
	content_1.len = 0; content_1.p = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	nimlf_(1378, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");	{
		if (!!(((*candidate_p0).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)5)))) goto LA4_;
		nimln_(1379);		nimln_(1375);		nimln_(1379);		result = NIM_FALSE;
		nimlf_(934, "/usr/lib/nim/lib/system.nim");		eqdestroy___pureZjson_u321(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
		nimln_(934);		eqdestroy___pureZjson_u321(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (title_1.p && !(title_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(title_1.p);
}
		goto BeforeRet_;
	}
LA4_: ;
	T6_.len = 0; T6_.p = NIM_NIL;
	nimlf_(1382, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");	{
		NIM_BOOL T9_;
		tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__3;
		NimStringV2 colontmpD__4;
		T9_ = (NIM_BOOL)0;
		T9_ = hasKey__pureZjson_u3707(candidate_p0, TM__HInI9a49a9a9bwob72ueo9cK5xA_22);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(T9_)) goto LA10_;
		nimln_(1383);		colontmpD_ = X5BX5D___pureZjson_u3594(candidate_p0, TM__HInI9a49a9a9bwob72ueo9cK5xA_23);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T9_ = ((*colontmpD_).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4));
LA10_: ;
		if (!T9_) goto LA11_;
		colontmpD__3 = NIM_NIL;
		colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
		nimln_(1381);		nimln_(1384);		colontmpD__3 = X5BX5D___pureZjson_u3594(candidate_p0, TM__HInI9a49a9a9bwob72ueo9cK5xA_26);
		if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
		colontmpD__4 = getStr__pureZjson_u551(colontmpD__3, TM__HInI9a49a9a9bwob72ueo9cK5xA_27);
		if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
		title_1 = plasticAssistantLearningKey__OOZOOZsrcZglaucoplastic_u4290(colontmpD__4);
		if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
		{
			LA13_:;
		}
		{
			oldNimErrFin13_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(394, "/usr/lib/nim/lib/system.nim");			if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
			nimln_(934);			eqdestroy___pureZjson_u321(colontmpD__3);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			*nimErr_ = oldNimErrFin13_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	goto LA7_;
LA11_: ;
	{
		nimlf_(1381, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");		nimln_(1386);		title_1 = TM__HInI9a49a9a9bwob72ueo9cK5xA_28;
	}
LA7_: ;
	T17_.len = 0; T17_.p = NIM_NIL;
	nimln_(1389);	{
		NIM_BOOL T20_;
		tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__5;
		NimStringV2 colontmpD__6;
		T20_ = (NIM_BOOL)0;
		T20_ = hasKey__pureZjson_u3707(candidate_p0, TM__HInI9a49a9a9bwob72ueo9cK5xA_29);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(T20_)) goto LA21_;
		nimln_(1390);		colontmpD__2 = X5BX5D___pureZjson_u3594(candidate_p0, TM__HInI9a49a9a9bwob72ueo9cK5xA_30);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T20_ = ((*colontmpD__2).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4));
LA21_: ;
		if (!T20_) goto LA22_;
		colontmpD__5 = NIM_NIL;
		colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
		nimln_(1388);		nimln_(1391);		colontmpD__5 = X5BX5D___pureZjson_u3594(candidate_p0, TM__HInI9a49a9a9bwob72ueo9cK5xA_31);
		if (NIM_UNLIKELY(*nimErr_)) goto LA24_;
		colontmpD__6 = getStr__pureZjson_u551(colontmpD__5, TM__HInI9a49a9a9bwob72ueo9cK5xA_32);
		if (NIM_UNLIKELY(*nimErr_)) goto LA24_;
		content_1 = plasticAssistantLearningKey__OOZOOZsrcZglaucoplastic_u4290(colontmpD__6);
		if (NIM_UNLIKELY(*nimErr_)) goto LA24_;
		{
			LA24_:;
		}
		{
			oldNimErrFin24_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(394, "/usr/lib/nim/lib/system.nim");			if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
			nimln_(934);			eqdestroy___pureZjson_u321(colontmpD__5);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			*nimErr_ = oldNimErrFin24_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	goto LA18_;
LA22_: ;
	{
		nimlf_(1388, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");		nimln_(1393);		content_1 = TM__HInI9a49a9a9bwob72ueo9cK5xA_33;
	}
LA18_: ;
	nimln_(1395);	nimln_(1402);	T28_ = (NIM_BOOL)0;
	nimln_(1401);	T29_ = (NIM_BOOL)0;
	nimln_(1396);	T29_ = contains__stdZenumutils_u50(TM__HInI9a49a9a9bwob72ueo9cK5xA_35, 4, title_1);
	if (T29_) goto LA30_;
	nimln_(1402);	T29_ = nsuStartsWith(content_1, TM__HInI9a49a9a9bwob72ueo9cK5xA_41);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
LA30_: ;
	T28_ = T29_;
	if (T28_) goto LA31_;
	nimln_(1403);	T28_ = nsuStartsWith(content_1, TM__HInI9a49a9a9bwob72ueo9cK5xA_43);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
LA31_: ;
	result = T28_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimlf_(934, "/usr/lib/nim/lib/system.nim");		eqdestroy___pureZjson_u321(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
		nimln_(934);		eqdestroy___pureZjson_u321(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (title_1.p && !(title_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(title_1.p);
}
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, plasticAssistantIsLearningNoise__OOZOOZsrcZglaucoplastic_u4363)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* candidate_p0) {
	NIM_BOOL result;
	NimStringV2 title_1;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD_;
	NimStringV2 content_1;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__2;
	NimStringV2 combined_1;
	NimStringV2 T6_;
NIM_BOOL oldNimErrFin13_;
	NimStringV2 T17_;
NIM_BOOL oldNimErrFin24_;
	NimStringV2 T28_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("plasticAssistantIsLearningNoise", "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	title_1.len = 0; title_1.p = NIM_NIL;
	colontmpD_ = NIM_NIL;
	content_1.len = 0; content_1.p = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	combined_1.len = 0; combined_1.p = NIM_NIL;
	nimlf_(1408, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");	{
		if (!!(((*candidate_p0).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)5)))) goto LA4_;
		nimln_(1409);		nimln_(1405);		nimln_(1409);		result = NIM_TRUE;
		nimlf_(394, "/usr/lib/nim/lib/system.nim");		if (combined_1.p && !(combined_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(combined_1.p);
}
		nimln_(934);		eqdestroy___pureZjson_u321(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
		nimln_(934);		eqdestroy___pureZjson_u321(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (title_1.p && !(title_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(title_1.p);
}
		goto BeforeRet_;
	}
LA4_: ;
	T6_.len = 0; T6_.p = NIM_NIL;
	nimlf_(1412, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");	{
		NIM_BOOL T9_;
		tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__3;
		NimStringV2 colontmpD__4;
		T9_ = (NIM_BOOL)0;
		T9_ = hasKey__pureZjson_u3707(candidate_p0, TM__HInI9a49a9a9bwob72ueo9cK5xA_44);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(T9_)) goto LA10_;
		nimln_(1413);		colontmpD_ = X5BX5D___pureZjson_u3594(candidate_p0, TM__HInI9a49a9a9bwob72ueo9cK5xA_45);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T9_ = ((*colontmpD_).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4));
LA10_: ;
		if (!T9_) goto LA11_;
		colontmpD__3 = NIM_NIL;
		colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
		nimln_(1411);		nimln_(1414);		colontmpD__3 = X5BX5D___pureZjson_u3594(candidate_p0, TM__HInI9a49a9a9bwob72ueo9cK5xA_46);
		if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
		colontmpD__4 = getStr__pureZjson_u551(colontmpD__3, TM__HInI9a49a9a9bwob72ueo9cK5xA_47);
		if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
		title_1 = plasticAssistantLearningKey__OOZOOZsrcZglaucoplastic_u4290(colontmpD__4);
		if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
		{
			LA13_:;
		}
		{
			oldNimErrFin13_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(394, "/usr/lib/nim/lib/system.nim");			if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
			nimln_(934);			eqdestroy___pureZjson_u321(colontmpD__3);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			*nimErr_ = oldNimErrFin13_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	goto LA7_;
LA11_: ;
	{
		nimlf_(1411, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");		nimln_(1416);		title_1 = TM__HInI9a49a9a9bwob72ueo9cK5xA_48;
	}
LA7_: ;
	T17_.len = 0; T17_.p = NIM_NIL;
	nimln_(1419);	{
		NIM_BOOL T20_;
		tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__5;
		NimStringV2 colontmpD__6;
		T20_ = (NIM_BOOL)0;
		T20_ = hasKey__pureZjson_u3707(candidate_p0, TM__HInI9a49a9a9bwob72ueo9cK5xA_49);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(T20_)) goto LA21_;
		nimln_(1420);		colontmpD__2 = X5BX5D___pureZjson_u3594(candidate_p0, TM__HInI9a49a9a9bwob72ueo9cK5xA_50);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T20_ = ((*colontmpD__2).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4));
LA21_: ;
		if (!T20_) goto LA22_;
		colontmpD__5 = NIM_NIL;
		colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
		nimln_(1418);		nimln_(1421);		colontmpD__5 = X5BX5D___pureZjson_u3594(candidate_p0, TM__HInI9a49a9a9bwob72ueo9cK5xA_51);
		if (NIM_UNLIKELY(*nimErr_)) goto LA24_;
		colontmpD__6 = getStr__pureZjson_u551(colontmpD__5, TM__HInI9a49a9a9bwob72ueo9cK5xA_52);
		if (NIM_UNLIKELY(*nimErr_)) goto LA24_;
		content_1 = plasticAssistantLearningKey__OOZOOZsrcZglaucoplastic_u4290(colontmpD__6);
		if (NIM_UNLIKELY(*nimErr_)) goto LA24_;
		{
			LA24_:;
		}
		{
			oldNimErrFin24_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(394, "/usr/lib/nim/lib/system.nim");			if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
			nimln_(934);			eqdestroy___pureZjson_u321(colontmpD__5);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			*nimErr_ = oldNimErrFin24_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	goto LA18_;
LA22_: ;
	{
		nimlf_(1418, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");		nimln_(1423);		content_1 = TM__HInI9a49a9a9bwob72ueo9cK5xA_53;
	}
LA18_: ;
	nimln_(1425);	T28_.len = 0; T28_.p = NIM_NIL;
	T28_ = rawNewString(title_1.len + content_1.len + 1);
appendString((&T28_), title_1);
appendString((&T28_), TM__HInI9a49a9a9bwob72ueo9cK5xA_54);
appendString((&T28_), content_1);
	combined_1 = T28_;
	{
		NimStringV2 phrase_1;
		NI i_1;
		phrase_1.len = 0; phrase_1.p = NIM_NIL;
		nimlf_(43, "/usr/lib/nim/lib/system/iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(44);			while (1) {
				nimlf_(1426, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");				phrase_1 = TM__HInI9a49a9a9bwob72ueo9cK5xA_55[(i_1)- 0];
				nimln_(1442);				{
					NIM_BOOL T34_;
					T34_ = (NIM_BOOL)0;
					T34_ = contains__pureZstrutils_u1900(combined_1, phrase_1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					if (!T34_) goto LA35_;
					nimln_(1443);					nimln_(1405);					nimln_(1443);					result = NIM_TRUE;
					nimlf_(394, "/usr/lib/nim/lib/system.nim");					if (combined_1.p && !(combined_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(combined_1.p);
}
					nimln_(934);					eqdestroy___pureZjson_u321(colontmpD__2);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(394);					if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
					nimln_(934);					eqdestroy___pureZjson_u321(colontmpD_);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(394);					if (title_1.p && !(title_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(title_1.p);
}
					goto BeforeRet_;
				}
LA35_: ;
				nimlf_(46, "/usr/lib/nim/lib/system/iterators.nim");				{
					if (!(((NI)13) <= i_1)) goto LA39_;
					goto LA30;
				}
LA39_: ;
				nimln_(13);				i_1 += ((NI)1);
			}
		} LA30: ;
	}
	nimlf_(1445, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");	result = NIM_FALSE;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimlf_(394, "/usr/lib/nim/lib/system.nim");		if (combined_1.p && !(combined_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(combined_1.p);
}
		nimln_(934);		eqdestroy___pureZjson_u321(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
		nimln_(934);		eqdestroy___pureZjson_u321(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (title_1.p && !(title_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(title_1.p);
}
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, plasticAssistantNormalizeLearningCandidate__OOZOOZsrcZglaucoplastic_u4518)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* existingThings_p0, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* candidate_p1) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	NimStringV2 title_1;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD_;
	NimStringV2 content_1;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__2;
	NimStringV2 titleKey_1;
	NimStringV2 contentKey_1;
	NimStringV2 scope_1;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__3;
	NimStringV2 T6_;
NIM_BOOL oldNimErrFin13_;
	NimStringV2 T17_;
NIM_BOOL oldNimErrFin24_;
	NimStringV2 T44_;
NIM_BOOL oldNimErrFin51_;
NIM_BOOL oldNimErrFin92_;
NIM_BOOL oldNimErrFin103_;
NIM_BOOL oldNimErrFin114_;
NIM_BOOL oldNimErrFin72_;
NIM_BOOL oldNimErrFin67_;
NIM_BOOL oldNimErrFin60_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("plasticAssistantNormalizeLearningCandidate", "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	title_1.len = 0; title_1.p = NIM_NIL;
	colontmpD_ = NIM_NIL;
	content_1.len = 0; content_1.p = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	titleKey_1.len = 0; titleKey_1.p = NIM_NIL;
	contentKey_1.len = 0; contentKey_1.p = NIM_NIL;
	scope_1.len = 0; scope_1.p = NIM_NIL;
	colontmpD__3 = NIM_NIL;
	nimlf_(1450, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");	{
		if (!!(((*candidate_p1).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)5)))) goto LA4_;
		nimln_(1451);		nimln_(1447);		nimln_(1451);		result = newJNull__pureZjson_u438();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimlf_(934, "/usr/lib/nim/lib/system.nim");		eqdestroy___pureZjson_u321(colontmpD__3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (scope_1.p && !(scope_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(scope_1.p);
}
		if (contentKey_1.p && !(contentKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(contentKey_1.p);
}
		if (titleKey_1.p && !(titleKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(titleKey_1.p);
}
		nimln_(934);		eqdestroy___pureZjson_u321(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
		nimln_(934);		eqdestroy___pureZjson_u321(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (title_1.p && !(title_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(title_1.p);
}
		goto BeforeRet_;
	}
LA4_: ;
	T6_.len = 0; T6_.p = NIM_NIL;
	nimlf_(1454, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");	{
		NIM_BOOL T9_;
		tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__4;
		NimStringV2 colontmpD__5;
		T9_ = (NIM_BOOL)0;
		T9_ = hasKey__pureZjson_u3707(candidate_p1, TM__HInI9a49a9a9bwob72ueo9cK5xA_3);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(T9_)) goto LA10_;
		nimln_(1455);		colontmpD_ = X5BX5D___pureZjson_u3594(candidate_p1, TM__HInI9a49a9a9bwob72ueo9cK5xA_10);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T9_ = ((*colontmpD_).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4));
LA10_: ;
		if (!T9_) goto LA11_;
		colontmpD__4 = NIM_NIL;
		colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
		nimln_(1453);		nimln_(1456);		colontmpD__4 = X5BX5D___pureZjson_u3594(candidate_p1, TM__HInI9a49a9a9bwob72ueo9cK5xA_11);
		if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
		colontmpD__5 = getStr__pureZjson_u551(colontmpD__4, TM__HInI9a49a9a9bwob72ueo9cK5xA_13);
		if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
		title_1 = nsuStrip(colontmpD__5, NIM_TRUE, NIM_TRUE, TM__HInI9a49a9a9bwob72ueo9cK5xA_14);
		if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
		{
			LA13_:;
		}
		{
			oldNimErrFin13_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(394, "/usr/lib/nim/lib/system.nim");			if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
			nimln_(934);			eqdestroy___pureZjson_u321(colontmpD__4);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			*nimErr_ = oldNimErrFin13_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	goto LA7_;
LA11_: ;
	{
		nimlf_(1453, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");		nimln_(1458);		title_1 = TM__HInI9a49a9a9bwob72ueo9cK5xA_15;
	}
LA7_: ;
	T17_.len = 0; T17_.p = NIM_NIL;
	nimln_(1461);	{
		NIM_BOOL T20_;
		tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__6;
		NimStringV2 colontmpD__7;
		T20_ = (NIM_BOOL)0;
		T20_ = hasKey__pureZjson_u3707(candidate_p1, TM__HInI9a49a9a9bwob72ueo9cK5xA_17);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(T20_)) goto LA21_;
		nimln_(1462);		colontmpD__2 = X5BX5D___pureZjson_u3594(candidate_p1, TM__HInI9a49a9a9bwob72ueo9cK5xA_18);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T20_ = ((*colontmpD__2).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4));
LA21_: ;
		if (!T20_) goto LA22_;
		colontmpD__6 = NIM_NIL;
		colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
		nimln_(1460);		nimln_(1463);		colontmpD__6 = X5BX5D___pureZjson_u3594(candidate_p1, TM__HInI9a49a9a9bwob72ueo9cK5xA_19);
		if (NIM_UNLIKELY(*nimErr_)) goto LA24_;
		colontmpD__7 = getStr__pureZjson_u551(colontmpD__6, TM__HInI9a49a9a9bwob72ueo9cK5xA_20);
		if (NIM_UNLIKELY(*nimErr_)) goto LA24_;
		content_1 = nsuStrip(colontmpD__7, NIM_TRUE, NIM_TRUE, TM__HInI9a49a9a9bwob72ueo9cK5xA_14);
		if (NIM_UNLIKELY(*nimErr_)) goto LA24_;
		{
			LA24_:;
		}
		{
			oldNimErrFin24_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(394, "/usr/lib/nim/lib/system.nim");			if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
			nimln_(934);			eqdestroy___pureZjson_u321(colontmpD__6);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			*nimErr_ = oldNimErrFin24_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	goto LA18_;
LA22_: ;
	{
		nimlf_(1460, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");		nimln_(1465);		content_1 = TM__HInI9a49a9a9bwob72ueo9cK5xA_21;
	}
LA18_: ;
	nimln_(1467);	{
		NIM_BOOL T30_;
		T30_ = (NIM_BOOL)0;
		T30_ = (title_1.len == ((NI)0));
		if (T30_) goto LA31_;
		T30_ = (content_1.len == ((NI)0));
LA31_: ;
		if (!T30_) goto LA32_;
		nimln_(1468);		nimln_(1447);		nimln_(1468);		result = newJNull__pureZjson_u438();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimlf_(934, "/usr/lib/nim/lib/system.nim");		eqdestroy___pureZjson_u321(colontmpD__3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (scope_1.p && !(scope_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(scope_1.p);
}
		if (contentKey_1.p && !(contentKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(contentKey_1.p);
}
		if (titleKey_1.p && !(titleKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(titleKey_1.p);
}
		nimln_(934);		eqdestroy___pureZjson_u321(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
		nimln_(934);		eqdestroy___pureZjson_u321(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (title_1.p && !(title_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(title_1.p);
}
		goto BeforeRet_;
	}
LA32_: ;
	nimlf_(1471, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");	{
		NIM_BOOL T36_;
		T36_ = (NIM_BOOL)0;
		T36_ = plasticAssistantIsNameLearningCandidate__OOZOOZsrcZglaucoplastic_u4293(candidate_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!T36_) goto LA37_;
		nimln_(1472);		nimln_(1447);		nimln_(1472);		result = newJNull__pureZjson_u438();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimlf_(934, "/usr/lib/nim/lib/system.nim");		eqdestroy___pureZjson_u321(colontmpD__3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (scope_1.p && !(scope_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(scope_1.p);
}
		if (contentKey_1.p && !(contentKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(contentKey_1.p);
}
		if (titleKey_1.p && !(titleKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(titleKey_1.p);
}
		nimln_(934);		eqdestroy___pureZjson_u321(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
		nimln_(934);		eqdestroy___pureZjson_u321(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (title_1.p && !(title_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(title_1.p);
}
		goto BeforeRet_;
	}
LA37_: ;
	nimlf_(1474, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");	{
		NIM_BOOL T41_;
		T41_ = (NIM_BOOL)0;
		T41_ = plasticAssistantIsLearningNoise__OOZOOZsrcZglaucoplastic_u4363(candidate_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!T41_) goto LA42_;
		nimln_(1475);		nimln_(1447);		nimln_(1475);		result = newJNull__pureZjson_u438();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimlf_(934, "/usr/lib/nim/lib/system.nim");		eqdestroy___pureZjson_u321(colontmpD__3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (scope_1.p && !(scope_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(scope_1.p);
}
		if (contentKey_1.p && !(contentKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(contentKey_1.p);
}
		if (titleKey_1.p && !(titleKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(titleKey_1.p);
}
		nimln_(934);		eqdestroy___pureZjson_u321(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
		nimln_(934);		eqdestroy___pureZjson_u321(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (title_1.p && !(title_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(title_1.p);
}
		goto BeforeRet_;
	}
LA42_: ;
	nimlf_(1477, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");	titleKey_1 = plasticAssistantLearningKey__OOZOOZsrcZglaucoplastic_u4290(title_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(1478);	contentKey_1 = plasticAssistantLearningKey__OOZOOZsrcZglaucoplastic_u4290(content_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T44_.len = 0; T44_.p = NIM_NIL;
	nimln_(1480);	{
		NIM_BOOL T47_;
		tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__8;
		T47_ = (NIM_BOOL)0;
		T47_ = hasKey__pureZjson_u3707(candidate_p1, TM__HInI9a49a9a9bwob72ueo9cK5xA_71);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(T47_)) goto LA48_;
		nimln_(1481);		colontmpD__3 = X5BX5D___pureZjson_u3594(candidate_p1, TM__HInI9a49a9a9bwob72ueo9cK5xA_72);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T47_ = ((*colontmpD__3).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4));
LA48_: ;
		if (!T47_) goto LA49_;
		colontmpD__8 = NIM_NIL;
		nimln_(1479);		nimln_(1482);		colontmpD__8 = X5BX5D___pureZjson_u3594(candidate_p1, TM__HInI9a49a9a9bwob72ueo9cK5xA_73);
		if (NIM_UNLIKELY(*nimErr_)) goto LA51_;
		scope_1 = getStr__pureZjson_u551(colontmpD__8, TM__HInI9a49a9a9bwob72ueo9cK5xA_74);
		if (NIM_UNLIKELY(*nimErr_)) goto LA51_;
		{
			LA51_:;
		}
		{
			oldNimErrFin51_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(934, "/usr/lib/nim/lib/system.nim");			eqdestroy___pureZjson_u321(colontmpD__8);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			*nimErr_ = oldNimErrFin51_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	goto LA45_;
LA49_: ;
	{
		nimlf_(1479, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");		nimln_(1484);		scope_1 = TM__HInI9a49a9a9bwob72ueo9cK5xA_76;
	}
LA45_: ;
	nimln_(1486);	{
		if (!((*existingThings_p0).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)6))) goto LA57_;
		{
			tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* existing_1;
			existing_1 = NIM_NIL;
			nimlf_(834, "/usr/lib/nim/lib/pure/json.nim");			{
				NimStringV2 colontmpD__9;
				NimStringV2 colontmpD__10;
				NimStringV2 T65_;
				if (!!(((*existingThings_p0).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)6)))) goto LA63_;
				colontmpD__9.len = 0; colontmpD__9.p = NIM_NIL;
				colontmpD__10.len = 0; colontmpD__10.p = NIM_NIL;
				T65_.len = 0; T65_.p = NIM_NIL;
				colontmpD__9 = dollar___pureZjson_u20((*existingThings_p0).kind);
				T65_ = rawNewString(colontmpD__9.len + 106);
appendString((&T65_), TM__HInI9a49a9a9bwob72ueo9cK5xA_78);
appendString((&T65_), colontmpD__9);
				colontmpD__10 = T65_;
				failedAssertImpl__stdZassertions_u95(colontmpD__10);
				if (NIM_UNLIKELY(*nimErr_)) goto LA60_;
				nimlf_(394, "/usr/lib/nim/lib/system.nim");				if (colontmpD__10.p && !(colontmpD__10.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__10.p);
}
				if (colontmpD__9.p && !(colontmpD__9.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__9.p);
}
			}
LA63_: ;
			{
				tySequence__jKinQKK5sMW4kMIzl4PsKQ colontmp_;
				tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** i_1;
				NI i_2;
				NI L_1;
				NI T68_;
				colontmp_.len = 0; colontmp_.p = NIM_NIL;
				i_1 = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg**)0;
				nimlf_(218, "/usr/lib/nim/lib/pure/json.nim");				if (!(((64 &((NU8)1<<((NU)(((*existingThings_p0).kind))&7U)))!=0))) 				{ raiseFieldErrorStr(TM__HInI9a49a9a9bwob72ueo9cK5xA_80, dollar___pureZjson_u20((*existingThings_p0).kind)); goto LA67_;
				}
				eqcopy___pureZjson_u257((&colontmp_), (*existingThings_p0)._kind_7.elems);
				if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
				nimlf_(249, "/usr/lib/nim/lib/system/iterators.nim");				i_2 = ((NI)0);
				nimln_(250);				T68_ = colontmp_.len;
				L_1 = T68_;
				{
					nimln_(251);					while (1) {
						if (!(i_2 < L_1)) goto LA70;
						nimlf_(835, "/usr/lib/nim/lib/pure/json.nim");						if (i_2 < 0 || i_2 >= colontmp_.len){ raiseIndexError2(i_2,colontmp_.len-1); goto LA67_;
						}
						i_1 = &colontmp_.p->data[i_2];
						nimlf_(934, "/usr/lib/nim/lib/system.nim");						eqcopy___pureZjson_u324(&existing_1, (*i_1));
						if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
						{
							tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__11;
							tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__12;
							NimStringV2 colontmpD__13;
							NimStringV2 existingTitle_1;
							tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__14;
							NimStringV2 existingContent_1;
							tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__15;
							NimStringV2 existingScope_1;
							tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__16;
							NimStringV2 T85_;
							NimStringV2 T96_;
							NimStringV2 T107_;
							colontmpD__11 = NIM_NIL;
							colontmpD__12 = NIM_NIL;
							colontmpD__13.len = 0; colontmpD__13.p = NIM_NIL;
							existingTitle_1.len = 0; existingTitle_1.p = NIM_NIL;
							colontmpD__14 = NIM_NIL;
							existingContent_1.len = 0; existingContent_1.p = NIM_NIL;
							colontmpD__15 = NIM_NIL;
							existingScope_1.len = 0; existingScope_1.p = NIM_NIL;
							colontmpD__16 = NIM_NIL;
							nimlf_(1488, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");							{
								if (!!(((*existing_1).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)5)))) goto LA75_;
								nimlf_(934, "/usr/lib/nim/lib/system.nim");								eqdestroy___pureZjson_u321(colontmpD__16);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingScope_1.p && !(existingScope_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingScope_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__15);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingContent_1.p && !(existingContent_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingContent_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__14);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingTitle_1.p && !(existingTitle_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingTitle_1.p);
}
								if (colontmpD__13.p && !(colontmpD__13.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__13.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__12);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								eqdestroy___pureZjson_u321(colontmpD__11);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimlf_(1489, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");								goto LA71;
							}
LA75_: ;
							nimln_(1491);							{
								NIM_BOOL T79_;
								NIM_BOOL T80_;
								nimln_(1492);								T79_ = (NIM_BOOL)0;
								nimln_(1491);								T80_ = (NIM_BOOL)0;
								T80_ = hasKey__pureZjson_u3707(existing_1, TM__HInI9a49a9a9bwob72ueo9cK5xA_82);
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
								if (!(T80_)) goto LA81_;
								nimln_(1492);								colontmpD__11 = X5BX5D___pureZjson_u3594(existing_1, TM__HInI9a49a9a9bwob72ueo9cK5xA_83);
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
								T80_ = ((*colontmpD__11).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4));
LA81_: ;
								T79_ = T80_;
								if (!(T79_)) goto LA82_;
								nimln_(1493);								colontmpD__12 = X5BX5D___pureZjson_u3594(existing_1, TM__HInI9a49a9a9bwob72ueo9cK5xA_84);
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
								colontmpD__13 = getStr__pureZjson_u551(colontmpD__12, TM__HInI9a49a9a9bwob72ueo9cK5xA_85);
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
								T79_ = eqStrings(colontmpD__13, TM__HInI9a49a9a9bwob72ueo9cK5xA_87);
LA82_: ;
								if (!T79_) goto LA83_;
								nimlf_(934, "/usr/lib/nim/lib/system.nim");								eqdestroy___pureZjson_u321(colontmpD__16);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingScope_1.p && !(existingScope_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingScope_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__15);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingContent_1.p && !(existingContent_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingContent_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__14);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingTitle_1.p && !(existingTitle_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingTitle_1.p);
}
								if (colontmpD__13.p && !(colontmpD__13.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__13.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__12);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								eqdestroy___pureZjson_u321(colontmpD__11);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimlf_(1494, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");								goto LA71;
							}
LA83_: ;
							T85_.len = 0; T85_.p = NIM_NIL;
							nimln_(1497);							{
								NIM_BOOL T88_;
								tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__17;
								NimStringV2 colontmpD__18;
								T88_ = (NIM_BOOL)0;
								T88_ = hasKey__pureZjson_u3707(existing_1, TM__HInI9a49a9a9bwob72ueo9cK5xA_88);
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
								if (!(T88_)) goto LA89_;
								nimln_(1498);								colontmpD__14 = X5BX5D___pureZjson_u3594(existing_1, TM__HInI9a49a9a9bwob72ueo9cK5xA_89);
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
								T88_ = ((*colontmpD__14).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4));
LA89_: ;
								if (!T88_) goto LA90_;
								colontmpD__17 = NIM_NIL;
								colontmpD__18.len = 0; colontmpD__18.p = NIM_NIL;
								nimln_(1496);								nimln_(1499);								colontmpD__17 = X5BX5D___pureZjson_u3594(existing_1, TM__HInI9a49a9a9bwob72ueo9cK5xA_90);
								if (NIM_UNLIKELY(*nimErr_)) goto LA92_;
								colontmpD__18 = getStr__pureZjson_u551(colontmpD__17, TM__HInI9a49a9a9bwob72ueo9cK5xA_91);
								if (NIM_UNLIKELY(*nimErr_)) goto LA92_;
								existingTitle_1 = plasticAssistantLearningKey__OOZOOZsrcZglaucoplastic_u4290(colontmpD__18);
								if (NIM_UNLIKELY(*nimErr_)) goto LA92_;
								{
									LA92_:;
								}
								{
									oldNimErrFin92_ = *nimErr_; *nimErr_ = NIM_FALSE;
									nimlf_(394, "/usr/lib/nim/lib/system.nim");									if (colontmpD__18.p && !(colontmpD__18.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__18.p);
}
									nimln_(934);									eqdestroy___pureZjson_u321(colontmpD__17);
									if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
									*nimErr_ = oldNimErrFin92_;
								}
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
							}
							goto LA86_;
LA90_: ;
							{
								nimlf_(1496, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");								nimln_(1501);								existingTitle_1 = TM__HInI9a49a9a9bwob72ueo9cK5xA_92;
							}
LA86_: ;
							T96_.len = 0; T96_.p = NIM_NIL;
							nimln_(1504);							{
								NIM_BOOL T99_;
								tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__19;
								NimStringV2 colontmpD__20;
								T99_ = (NIM_BOOL)0;
								T99_ = hasKey__pureZjson_u3707(existing_1, TM__HInI9a49a9a9bwob72ueo9cK5xA_93);
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
								if (!(T99_)) goto LA100_;
								nimln_(1505);								colontmpD__15 = X5BX5D___pureZjson_u3594(existing_1, TM__HInI9a49a9a9bwob72ueo9cK5xA_94);
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
								T99_ = ((*colontmpD__15).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4));
LA100_: ;
								if (!T99_) goto LA101_;
								colontmpD__19 = NIM_NIL;
								colontmpD__20.len = 0; colontmpD__20.p = NIM_NIL;
								nimln_(1503);								nimln_(1506);								colontmpD__19 = X5BX5D___pureZjson_u3594(existing_1, TM__HInI9a49a9a9bwob72ueo9cK5xA_95);
								if (NIM_UNLIKELY(*nimErr_)) goto LA103_;
								colontmpD__20 = getStr__pureZjson_u551(colontmpD__19, TM__HInI9a49a9a9bwob72ueo9cK5xA_96);
								if (NIM_UNLIKELY(*nimErr_)) goto LA103_;
								existingContent_1 = plasticAssistantLearningKey__OOZOOZsrcZglaucoplastic_u4290(colontmpD__20);
								if (NIM_UNLIKELY(*nimErr_)) goto LA103_;
								{
									LA103_:;
								}
								{
									oldNimErrFin103_ = *nimErr_; *nimErr_ = NIM_FALSE;
									nimlf_(394, "/usr/lib/nim/lib/system.nim");									if (colontmpD__20.p && !(colontmpD__20.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__20.p);
}
									nimln_(934);									eqdestroy___pureZjson_u321(colontmpD__19);
									if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
									*nimErr_ = oldNimErrFin103_;
								}
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
							}
							goto LA97_;
LA101_: ;
							{
								nimlf_(1503, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");								nimln_(1508);								existingContent_1 = TM__HInI9a49a9a9bwob72ueo9cK5xA_97;
							}
LA97_: ;
							T107_.len = 0; T107_.p = NIM_NIL;
							nimln_(1511);							{
								NIM_BOOL T110_;
								tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD__21;
								T110_ = (NIM_BOOL)0;
								T110_ = hasKey__pureZjson_u3707(existing_1, TM__HInI9a49a9a9bwob72ueo9cK5xA_98);
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
								if (!(T110_)) goto LA111_;
								nimln_(1512);								colontmpD__16 = X5BX5D___pureZjson_u3594(existing_1, TM__HInI9a49a9a9bwob72ueo9cK5xA_99);
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
								T110_ = ((*colontmpD__16).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4));
LA111_: ;
								if (!T110_) goto LA112_;
								colontmpD__21 = NIM_NIL;
								nimln_(1510);								nimln_(1513);								colontmpD__21 = X5BX5D___pureZjson_u3594(existing_1, TM__HInI9a49a9a9bwob72ueo9cK5xA_100);
								if (NIM_UNLIKELY(*nimErr_)) goto LA114_;
								existingScope_1 = getStr__pureZjson_u551(colontmpD__21, TM__HInI9a49a9a9bwob72ueo9cK5xA_101);
								if (NIM_UNLIKELY(*nimErr_)) goto LA114_;
								{
									LA114_:;
								}
								{
									oldNimErrFin114_ = *nimErr_; *nimErr_ = NIM_FALSE;
									nimlf_(934, "/usr/lib/nim/lib/system.nim");									eqdestroy___pureZjson_u321(colontmpD__21);
									if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
									*nimErr_ = oldNimErrFin114_;
								}
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
							}
							goto LA108_;
LA112_: ;
							{
								nimlf_(1510, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");								nimln_(1515);								existingScope_1 = TM__HInI9a49a9a9bwob72ueo9cK5xA_102;
							}
LA108_: ;
							nimln_(1517);							{
								NIM_BOOL T120_;
								T120_ = (NIM_BOOL)0;
								T120_ = (((NI)0) < existingContent_1.len);
								if (!(T120_)) goto LA121_;
								nimln_(1518);								T120_ = eqStrings(existingContent_1, contentKey_1);
LA121_: ;
								if (!T120_) goto LA122_;
								nimln_(1519);								nimln_(1447);								nimln_(1519);								result = newJNull__pureZjson_u438();
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
								nimlf_(934, "/usr/lib/nim/lib/system.nim");								eqdestroy___pureZjson_u321(colontmpD__16);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingScope_1.p && !(existingScope_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingScope_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__15);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingContent_1.p && !(existingContent_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingContent_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__14);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingTitle_1.p && !(existingTitle_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingTitle_1.p);
}
								if (colontmpD__13.p && !(colontmpD__13.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__13.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__12);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								eqdestroy___pureZjson_u321(colontmpD__11);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimlf_(218, "/usr/lib/nim/lib/pure/json.nim");								eqdestroy___pureZjson_u254(colontmp_);
								if (NIM_UNLIKELY(*nimErr_)) goto LA60_;
								nimlf_(934, "/usr/lib/nim/lib/system.nim");								eqdestroy___pureZjson_u321(existing_1);
								if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
								eqdestroy___pureZjson_u321(colontmpD__3);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								nimln_(394);								if (scope_1.p && !(scope_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(scope_1.p);
}
								if (contentKey_1.p && !(contentKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(contentKey_1.p);
}
								if (titleKey_1.p && !(titleKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(titleKey_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__2);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								nimln_(394);								if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD_);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								nimln_(394);								if (title_1.p && !(title_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(title_1.p);
}
								goto BeforeRet_;
							}
LA122_: ;
							nimlf_(1521, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");							{
								NIM_BOOL T126_;
								NIM_BOOL T127_;
								nimln_(1522);								T126_ = (NIM_BOOL)0;
								nimln_(1521);								T127_ = (NIM_BOOL)0;
								T127_ = (((NI)0) < existingTitle_1.len);
								if (!(T127_)) goto LA128_;
								nimln_(1522);								T127_ = eqStrings(existingTitle_1, titleKey_1);
LA128_: ;
								T126_ = T127_;
								if (!(T126_)) goto LA129_;
								nimln_(1523);								T126_ = eqStrings(existingScope_1, scope_1);
LA129_: ;
								if (!T126_) goto LA130_;
								nimln_(1524);								{
									if (!eqStrings(existingContent_1, contentKey_1)) goto LA134_;
									nimln_(1525);									nimln_(1447);									nimln_(1525);									result = newJNull__pureZjson_u438();
									if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
									nimlf_(934, "/usr/lib/nim/lib/system.nim");									eqdestroy___pureZjson_u321(colontmpD__16);
									if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
									nimln_(394);									if (existingScope_1.p && !(existingScope_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingScope_1.p);
}
									nimln_(934);									eqdestroy___pureZjson_u321(colontmpD__15);
									if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
									nimln_(394);									if (existingContent_1.p && !(existingContent_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingContent_1.p);
}
									nimln_(934);									eqdestroy___pureZjson_u321(colontmpD__14);
									if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
									nimln_(394);									if (existingTitle_1.p && !(existingTitle_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingTitle_1.p);
}
									if (colontmpD__13.p && !(colontmpD__13.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__13.p);
}
									nimln_(934);									eqdestroy___pureZjson_u321(colontmpD__12);
									if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
									eqdestroy___pureZjson_u321(colontmpD__11);
									if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
									nimlf_(218, "/usr/lib/nim/lib/pure/json.nim");									eqdestroy___pureZjson_u254(colontmp_);
									if (NIM_UNLIKELY(*nimErr_)) goto LA60_;
									nimlf_(934, "/usr/lib/nim/lib/system.nim");									eqdestroy___pureZjson_u321(existing_1);
									if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
									eqdestroy___pureZjson_u321(colontmpD__3);
									if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
									nimln_(394);									if (scope_1.p && !(scope_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(scope_1.p);
}
									if (contentKey_1.p && !(contentKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(contentKey_1.p);
}
									if (titleKey_1.p && !(titleKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(titleKey_1.p);
}
									nimln_(934);									eqdestroy___pureZjson_u321(colontmpD__2);
									if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
									nimln_(394);									if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
									nimln_(934);									eqdestroy___pureZjson_u321(colontmpD_);
									if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
									nimln_(394);									if (title_1.p && !(title_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(title_1.p);
}
									goto BeforeRet_;
								}
LA134_: ;
								nimlf_(1526, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");								nimln_(1447);								nimln_(1526);								result = copy__pureZjson_u4783(candidate_p1);
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
								nimlf_(934, "/usr/lib/nim/lib/system.nim");								eqdestroy___pureZjson_u321(colontmpD__16);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingScope_1.p && !(existingScope_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingScope_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__15);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingContent_1.p && !(existingContent_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingContent_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__14);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingTitle_1.p && !(existingTitle_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingTitle_1.p);
}
								if (colontmpD__13.p && !(colontmpD__13.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__13.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__12);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								eqdestroy___pureZjson_u321(colontmpD__11);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimlf_(218, "/usr/lib/nim/lib/pure/json.nim");								eqdestroy___pureZjson_u254(colontmp_);
								if (NIM_UNLIKELY(*nimErr_)) goto LA60_;
								nimlf_(934, "/usr/lib/nim/lib/system.nim");								eqdestroy___pureZjson_u321(existing_1);
								if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
								eqdestroy___pureZjson_u321(colontmpD__3);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								nimln_(394);								if (scope_1.p && !(scope_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(scope_1.p);
}
								if (contentKey_1.p && !(contentKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(contentKey_1.p);
}
								if (titleKey_1.p && !(titleKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(titleKey_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__2);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								nimln_(394);								if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD_);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								nimln_(394);								if (title_1.p && !(title_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(title_1.p);
}
								goto BeforeRet_;
							}
LA130_: ;
							nimlf_(1528, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");							{
								NIM_BOOL T138_;
								NIM_BOOL T139_;
								NIM_BOOL T140_;
								nimln_(1530);								T138_ = (NIM_BOOL)0;
								nimln_(1529);								T139_ = (NIM_BOOL)0;
								nimln_(1528);								T140_ = (NIM_BOOL)0;
								T140_ = nsuStartsWith(scope_1, TM__HInI9a49a9a9bwob72ueo9cK5xA_104);
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
								if (!(T140_)) goto LA141_;
								nimln_(1529);								T140_ = eqStrings(existingScope_1, TM__HInI9a49a9a9bwob72ueo9cK5xA_105);
LA141_: ;
								T139_ = T140_;
								if (!(T139_)) goto LA142_;
								nimln_(1530);								T139_ = (((NI)0) < existingTitle_1.len);
LA142_: ;
								T138_ = T139_;
								if (!(T138_)) goto LA143_;
								nimln_(1531);								T138_ = eqStrings(existingTitle_1, titleKey_1);
LA143_: ;
								if (!T138_) goto LA144_;
								nimln_(1532);								nimln_(1447);								nimln_(1532);								result = newJNull__pureZjson_u438();
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
								nimlf_(934, "/usr/lib/nim/lib/system.nim");								eqdestroy___pureZjson_u321(colontmpD__16);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingScope_1.p && !(existingScope_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingScope_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__15);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingContent_1.p && !(existingContent_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingContent_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__14);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingTitle_1.p && !(existingTitle_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingTitle_1.p);
}
								if (colontmpD__13.p && !(colontmpD__13.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__13.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__12);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								eqdestroy___pureZjson_u321(colontmpD__11);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimlf_(218, "/usr/lib/nim/lib/pure/json.nim");								eqdestroy___pureZjson_u254(colontmp_);
								if (NIM_UNLIKELY(*nimErr_)) goto LA60_;
								nimlf_(934, "/usr/lib/nim/lib/system.nim");								eqdestroy___pureZjson_u321(existing_1);
								if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
								eqdestroy___pureZjson_u321(colontmpD__3);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								nimln_(394);								if (scope_1.p && !(scope_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(scope_1.p);
}
								if (contentKey_1.p && !(contentKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(contentKey_1.p);
}
								if (titleKey_1.p && !(titleKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(titleKey_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__2);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								nimln_(394);								if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD_);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								nimln_(394);								if (title_1.p && !(title_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(title_1.p);
}
								goto BeforeRet_;
							}
LA144_: ;
							{
								LA72_:;
							}
							{
								oldNimErrFin72_ = *nimErr_; *nimErr_ = NIM_FALSE;
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__16);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingScope_1.p && !(existingScope_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingScope_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__15);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingContent_1.p && !(existingContent_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingContent_1.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__14);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								nimln_(394);								if (existingTitle_1.p && !(existingTitle_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(existingTitle_1.p);
}
								if (colontmpD__13.p && !(colontmpD__13.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__13.p);
}
								nimln_(934);								eqdestroy___pureZjson_u321(colontmpD__12);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								eqdestroy___pureZjson_u321(colontmpD__11);
								if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
								*nimErr_ = oldNimErrFin72_;
							}
							if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
						} LA71: ;
						nimlf_(13, "/usr/lib/nim/lib/system/iterators.nim");						i_2 += ((NI)1);
						nimln_(254);						{
							NI T150_;
							T150_ = colontmp_.len;
							if (!!((T150_ == L_1))) goto LA151_;
							failedAssertImpl__stdZassertions_u95(TM__HInI9a49a9a9bwob72ueo9cK5xA_107);
							if (NIM_UNLIKELY(*nimErr_)) goto LA67_;
						}
LA151_: ;
					} LA70: ;
				}
				{
					LA67_:;
				}
				{
					oldNimErrFin67_ = *nimErr_; *nimErr_ = NIM_FALSE;
					nimlf_(218, "/usr/lib/nim/lib/pure/json.nim");					eqdestroy___pureZjson_u254(colontmp_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA60_;
					*nimErr_ = oldNimErrFin67_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA60_;
			}
			{
				LA60_:;
			}
			{
				oldNimErrFin60_ = *nimErr_; *nimErr_ = NIM_FALSE;
				nimlf_(934, "/usr/lib/nim/lib/system.nim");				eqdestroy___pureZjson_u321(existing_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				*nimErr_ = oldNimErrFin60_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
	}
LA57_: ;
	nimlf_(1534, "/home/icarogdo/dev/glaucoplastic/src/glaucoplastic.nim");	result = copy__pureZjson_u4783(candidate_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimlf_(934, "/usr/lib/nim/lib/system.nim");		eqdestroy___pureZjson_u321(colontmpD__3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (scope_1.p && !(scope_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(scope_1.p);
}
		if (contentKey_1.p && !(contentKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(contentKey_1.p);
}
		if (titleKey_1.p && !(titleKey_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(titleKey_1.p);
}
		nimln_(934);		eqdestroy___pureZjson_u321(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
		nimln_(934);		eqdestroy___pureZjson_u321(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(394);		if (title_1.p && !(title_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(title_1.p);
}
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
