/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/usr/lib/nim/lib -I/home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751 -o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@pjson.nim.c.o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@pjson.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw;
typedef struct tySequence__focVCaRY1axNSYW9at2kyIQ tySequence__focVCaRY1axNSYW9at2kyIQ;
typedef struct tySequence__focVCaRY1axNSYW9at2kyIQ_Content tySequence__focVCaRY1axNSYW9at2kyIQ_Content;
typedef struct tySequence__jKinQKK5sMW4kMIzl4PsKQ tySequence__jKinQKK5sMW4kMIzl4PsKQ;
typedef struct tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content;
typedef struct tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA;
typedef struct tyTuple__yeSFujPok8SfAGi9apNECrw tyTuple__yeSFujPok8SfAGi9apNECrw;
typedef struct tyObject_NimRawSeq__9cILcSEMTM25Wr2S8osw5Bw tyObject_NimRawSeq__9cILcSEMTM25Wr2S8osw5Bw;
typedef struct tyTuple__djYX1zUye8QMbG2U8KWWqg tyTuple__djYX1zUye8QMbG2U8KWWqg;
typedef NU8 tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__focVCaRY1axNSYW9at2kyIQ {
  NI len; tySequence__focVCaRY1axNSYW9at2kyIQ_Content* p;
};
struct tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw {
	tySequence__focVCaRY1axNSYW9at2kyIQ data;
	NI counter;
	NI first;
	NI last;
};
struct tySequence__jKinQKK5sMW4kMIzl4PsKQ {
  NI len; tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content* p;
};
struct tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg {
	NIM_BOOL isUnquoted;
	tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A kind;
union{
	struct {
	NimStringV2 str;
} _kind_1;
	struct {
	NI64 num;
} _kind_2;
	struct {
	NF fnum;
} _kind_3;
	struct {
	NIM_BOOL bval;
} _kind_4;
	struct {
	tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw fields;
} _kind_6;
	struct {
	tySequence__jKinQKK5sMW4kMIzl4PsKQ elems;
} _kind_7;
};
};
struct tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA {
	NI rc;
	NI rootIdx;
};
struct tyTuple__yeSFujPok8SfAGi9apNECrw {
	NimStringV2 Field0;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* Field1;
};
struct tyObject_NimRawSeq__9cILcSEMTM25Wr2S8osw5Bw {
	NI len;
	void* p;
};
struct tyTuple__djYX1zUye8QMbG2U8KWWqg {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* Field3;
};
struct tySequence__focVCaRY1axNSYW9at2kyIQ_Content { NI cap; tyTuple__djYX1zUye8QMbG2U8KWWqg data[SEQ_DECL_SIZE]; };
struct tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content { NI cap; tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJArray__pureZjson_u503)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__pureZjson_u659)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* father_p0, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* child_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__pureZjson_u671)(tySequence__jKinQKK5sMW4kMIzl4PsKQ* x_p0, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZjson_u20)(tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A e_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldErrorStr)(NimStringV2 f_p0, NimStringV2 discVal_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, eqdup___pureZjson_u327)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* src_p0);
static N_INLINE(void, nimIncRef)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJObject__pureZjson_u440)(void);
N_LIB_PRIVATE N_NIMCALL(void, initOrderedTable__pureZjson_u454)(NI initialSize_p0, tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw* Result);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u91)(tySequence__focVCaRY1axNSYW9at2kyIQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u254)(tySequence__jKinQKK5sMW4kMIzl4PsKQ dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastDyn)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, unregisterCycle__system_u3203)(tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u67)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZjson_u740)(tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw* t_p0, NimStringV2 key_p1, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* val_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2775)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZjson_u3028)(tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw* t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2772)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLen__pureZjson_u276)(tySequence__jKinQKK5sMW4kMIzl4PsKQ* s_p0, NI newlen_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJString__pureZjson_u42)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJInt__pureZjson_u429)(NI64 n_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJFloat__pureZjson_u432)(NF n_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJBool__pureZjson_u435)(NIM_BOOL b_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJNull__pureZjson_u438)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u486)(tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw* dest_p0, tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw* src_p1);
static N_INLINE(NI, len__pureZjson_u2618)(tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw* t_p0);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u324)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** dest_p0, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, copy__pureZjson_u4783)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u321)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u483)(tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u257)(tySequence__jKinQKK5sMW4kMIzl4PsKQ* dest_p0, tySequence__jKinQKK5sMW4kMIzl4PsKQ src_p1);
static const struct {
  NI cap; NIM_CHAR data[63+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_2 = { 63 | NIM_STRLIT_FLAG, "/usr/lib/nim/lib/pure/json.nim(307, 3) `father.kind == JArray` " };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_3 = {63, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_2};
static const struct {
  NI cap; NIM_CHAR data[69+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_4 = { 69 | NIM_STRLIT_FLAG, "field \'elems\' is not accessible for type \'JsonNodeObj\' using \'kind = " };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_5 = {69, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_4};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_6 = { 5 | NIM_STRLIT_FLAG, "JNull" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_7 = {5, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_6};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_8 = { 5 | NIM_STRLIT_FLAG, "JBool" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_9 = {5, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_8};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_10 = { 4 | NIM_STRLIT_FLAG, "JInt" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_11 = {4, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_10};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_12 = { 6 | NIM_STRLIT_FLAG, "JFloat" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_13 = {6, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_12};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_14 = { 7 | NIM_STRLIT_FLAG, "JString" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_15 = {7, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_14};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_16 = { 7 | NIM_STRLIT_FLAG, "JObject" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_17 = {7, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_16};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_18 = { 6 | NIM_STRLIT_FLAG, "JArray" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_19 = {6, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_18};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_20 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_21 = {0, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_20};
static const struct {
  NI cap; NIM_CHAR data[70+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_22 = { 70 | NIM_STRLIT_FLAG, "field \'fields\' is not accessible for type \'JsonNodeObj\' using \'kind = " };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_23 = {70, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_22};
static const struct {
  NI cap; NIM_CHAR data[62+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_24 = { 62 | NIM_STRLIT_FLAG, "/usr/lib/nim/lib/pure/json.nim(568, 9) `node.kind == JObject` " };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_25 = {62, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_24};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_26 = {70, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_22};
static const struct {
  NI cap; NIM_CHAR data[67+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_27 = { 67 | NIM_STRLIT_FLAG, "field \'str\' is not accessible for type \'JsonNodeObj\' using \'kind = " };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_28 = {67, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_27};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_29 = {67, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_27};
static const struct {
  NI cap; NIM_CHAR data[67+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_30 = { 67 | NIM_STRLIT_FLAG, "field \'num\' is not accessible for type \'JsonNodeObj\' using \'kind = " };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_31 = {67, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_30};
static const struct {
  NI cap; NIM_CHAR data[68+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_32 = { 68 | NIM_STRLIT_FLAG, "field \'fnum\' is not accessible for type \'JsonNodeObj\' using \'kind = " };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_33 = {68, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_32};
static const struct {
  NI cap; NIM_CHAR data[68+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_34 = { 68 | NIM_STRLIT_FLAG, "field \'bval\' is not accessible for type \'JsonNodeObj\' using \'kind = " };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_35 = {68, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_34};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_36 = {70, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_22};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_37 = {70, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_22};
static const struct {
  NI cap; NIM_CHAR data[124+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_38 = { 124 | NIM_STRLIT_FLAG, "/usr/lib/nim/lib/pure/collections/tables.nim(1822, 11) `len(t) == L` the length of the table changed while iterating over it" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_39 = {124, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_38};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_40 = {69, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_4};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_41 = {69, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_4};
static const struct {
  NI cap; NIM_CHAR data[114+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_42 = { 114 | NIM_STRLIT_FLAG, "/usr/lib/nim/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_43 = {114, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_42};
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJArray__pureZjson_u503)(void) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
	nimfr_("newJArray", "/usr/lib/nim/lib/pure/json.nim");
	nimlf_(249, "/usr/lib/nim/lib/pure/json.nim");	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)6);
	(*T1_)._kind_7.elems.len = 0; (*T1_)._kind_7.elems.p = (tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content*) newSeqPayload(0, sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*));
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZjson_u20)(tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A e_p0) {
	NimStringV2 result;
	switch (e_p0) {
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)0):
	{
		result = TM__9b9bytt1stv9cZ8uqII7HFgew_7;
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)1):
	{
		result = TM__9b9bytt1stv9cZ8uqII7HFgew_9;
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)2):
	{
		result = TM__9b9bytt1stv9cZ8uqII7HFgew_11;
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)3):
	{
		result = TM__9b9bytt1stv9cZ8uqII7HFgew_13;
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4):
	{
		result = TM__9b9bytt1stv9cZ8uqII7HFgew_15;
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)5):
	{
		result = TM__9b9bytt1stv9cZ8uqII7HFgew_17;
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)6):
	{
		result = TM__9b9bytt1stv9cZ8uqII7HFgew_19;
	}
	break;
	default:
	{
		result = TM__9b9bytt1stv9cZ8uqII7HFgew_21;
	}
	break;
	}
	return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/usr/lib/nim/lib/system/arithmetics.nim");
	nimlf_(377, "/usr/lib/nim/lib/system/arithmetics.nim");	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/usr/lib/nim/lib/system/arithmetics.nim");
	nimln_(366);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI T1_;
	NI T2_;
	nimfr_("nimIncRef", "/usr/lib/nim/lib/system/arc.nim");
	nimlf_(88, "/usr/lib/nim/lib/system/arc.nim");	nimln_(60);	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	nimln_(88);	nimln_(60);	T2_ = (NI)0;
	T2_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	nimln_(88);	(*((tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA*) (T1_))).rc = pluspercent___system_u793((*((tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA*) (T2_))).rc, ((NI)16));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, eqdup___pureZjson_u327)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* src_p0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	result = src_p0;
	{
		if (!src_p0) goto LA3_;
		nimIncRef(src_p0);
	}
LA3_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, add__pureZjson_u659)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* father_p0, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* child_p1) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("add", "/usr/lib/nim/lib/pure/json.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(307, "/usr/lib/nim/lib/pure/json.nim");	{
		if (!!(((*father_p0).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)6)))) goto LA3_;
		failedAssertImpl__stdZassertions_u95(TM__9b9bytt1stv9cZ8uqII7HFgew_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimln_(308);	if (!(((64 &((NU8)1<<((NU)(((*father_p0).kind))&7U)))!=0))) 	{ raiseFieldErrorStr(TM__9b9bytt1stv9cZ8uqII7HFgew_5, dollar___pureZjson_u20((*father_p0).kind)); goto BeforeRet_;
	}
	nimlf_(934, "/usr/lib/nim/lib/system.nim");	colontmpD_ = eqdup___pureZjson_u327(child_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(308, "/usr/lib/nim/lib/pure/json.nim");	add__pureZjson_u671((&(*father_p0)._kind_7.elems), colontmpD_);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, percent___OOZOOZsrcZglaucoplastic_u252)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** elements_p0, NI elements_p0Len_0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
NIM_BOOL* nimErr_;
	nimfr_("%", "/usr/lib/nim/lib/pure/json.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimln_(368);	result = newJArray__pureZjson_u503();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** elem_1;
		NI i_1;
		elem_1 = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg**)0;
		nimlf_(18, "/usr/lib/nim/lib/system/iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(19);			while (1) {
				if (!(i_1 < elements_p0Len_0)) goto LA3;
				nimlf_(369, "/usr/lib/nim/lib/pure/json.nim");				if (i_1 < 0 || i_1 >= elements_p0Len_0){ raiseIndexError2(i_1,elements_p0Len_0-1); goto BeforeRet_;
				}
				elem_1 = &elements_p0[i_1];
				add__pureZjson_u659(result, (*elem_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(13, "/usr/lib/nim/lib/system/iterators.nim");				i_1 += ((NI)1);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastDyn", "/usr/lib/nim/lib/system/orc.nim");
	nimlf_(530, "/usr/lib/nim/lib/system/orc.nim");	result = NIM_FALSE;
	nimln_(531);	{
		tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(532);		nimlf_(60, "/usr/lib/nim/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA*) (T5_));
		nimlf_(533, "/usr/lib/nim/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(534);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(537);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(539);		{
			if (!result) goto LA13_;
			nimln_(540);			{
				if (!(((NI)0) < (*cell_1).rootIdx)) goto LA17_;
				nimln_(541);				unregisterCycle__system_u3203(cell_1);
			}
LA17_: ;
		}
LA13_: ;
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u254)(tySequence__jKinQKK5sMW4kMIzl4PsKQ dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLastDyn(dest_p0.p->data[colontmp_]);
				if (!T6_) goto LA7_;
				eqdestroy___pureZjson_u67((&(*dest_p0.p->data[colontmp_])));
				nimRawDispose(dest_p0.p->data[colontmp_], ((NI)8));
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u67)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* dest_p0) {
	switch ((*dest_p0).kind) {
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4):
	{
		if ((*dest_p0)._kind_1.str.p && !((*dest_p0)._kind_1.str.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0)._kind_1.str.p);
}
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)2):
	{
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)3):
	{
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)1):
	{
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)0):
	{
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)5):
	{
		eqdestroy___pureZjson_u91((*dest_p0)._kind_6.fields.data);
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)6):
	{
		eqdestroy___pureZjson_u254((*dest_p0)._kind_7.elems);
	}
	break;
	default: __builtin_unreachable();
	}
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJObject__pureZjson_u440)(void) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
NIM_BOOL* nimErr_;
	nimfr_("newJObject", "/usr/lib/nim/lib/pure/json.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimlf_(245, "/usr/lib/nim/lib/pure/json.nim");	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)5);
	initOrderedTable__pureZjson_u454(((NI)2), (&(*T1_)._kind_6.fields));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = T1_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZjson_u330)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** dest_p0, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* src_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastDyn((*dest_p0));
		if (!T3_) goto LA4_;
		eqdestroy___pureZjson_u67((&(*(*dest_p0))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA4_: ;
	(*dest_p0) = src_p1;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZjson_u318)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, percent___pureZjson_u2195)(tyTuple__yeSFujPok8SfAGi9apNECrw* keyVals_p0, NI keyVals_p0Len_0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
NIM_BOOL* nimErr_;
	nimfr_("%", "/usr/lib/nim/lib/pure/json.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimln_(360);	{
		if (!(keyVals_p0Len_0 == ((NI)0))) goto LA3_;
		nimln_(358);		nimln_(360);		result = newJArray__pureZjson_u503();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(361);	result = newJObject__pureZjson_u440();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NimStringV2* key_1;
		tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** val_1;
		NI i_1;
		key_1 = (NimStringV2*)0;
		val_1 = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg**)0;
		nimlf_(18, "/usr/lib/nim/lib/system/iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(19);			while (1) {
				tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD_;
				if (!(i_1 < keyVals_p0Len_0)) goto LA7;
				nimlf_(362, "/usr/lib/nim/lib/pure/json.nim");				if (i_1 < 0 || i_1 >= keyVals_p0Len_0){ raiseIndexError2(i_1,keyVals_p0Len_0-1); goto BeforeRet_;
				}
				key_1 = (&keyVals_p0[i_1].Field0);
				if (i_1 < 0 || i_1 >= keyVals_p0Len_0){ raiseIndexError2(i_1,keyVals_p0Len_0-1); goto BeforeRet_;
				}
				val_1 = &keyVals_p0[i_1].Field1;
				if (!(((32 &((NU8)1<<((NU)(((*result).kind))&7U)))!=0))) 				{ raiseFieldErrorStr(TM__9b9bytt1stv9cZ8uqII7HFgew_23, dollar___pureZjson_u20((*result).kind)); goto BeforeRet_;
				}
				nimlf_(934, "/usr/lib/nim/lib/system.nim");				colontmpD_ = eqdup___pureZjson_u327((*val_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(362, "/usr/lib/nim/lib/pure/json.nim");				X5BX5Deq___pureZjson_u740((&(*result)._kind_6.fields), (*key_1), colontmpD_);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(13, "/usr/lib/nim/lib/system/iterators.nim");				i_1 += ((NI)1);
			} LA7: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, percent___pureZjson_u2166)(NimStringV2 s_p0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	NimStringV2 colontmpD_;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
	nimfr_("%", "/usr/lib/nim/lib/pure/json.nim");
	nimlf_(317, "/usr/lib/nim/lib/pure/json.nim");	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4);
	nimlf_(1715, "/usr/lib/nim/lib/system.nim");	colontmpD_ = eqdup___system_u2775(s_p0);
	(*T1_)._kind_1.str = colontmpD_;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u321)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastDyn(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___pureZjson_u67((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJNull__pureZjson_u438)(void) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
	nimfr_("newJNull", "/usr/lib/nim/lib/pure/json.nim");
	nimlf_(241, "/usr/lib/nim/lib/pure/json.nim");	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)0);
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZjson_u3707)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* node_p0, NimStringV2 key_p1) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("hasKey", "/usr/lib/nim/lib/pure/json.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(568);	{
		if (!!(((*node_p0).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)5)))) goto LA3_;
		failedAssertImpl__stdZassertions_u95(TM__9b9bytt1stv9cZ8uqII7HFgew_25);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimln_(569);	if (!(((32 &((NU8)1<<((NU)(((*node_p0).kind))&7U)))!=0))) 	{ raiseFieldErrorStr(TM__9b9bytt1stv9cZ8uqII7HFgew_26, dollar___pureZjson_u20((*node_p0).kind)); goto BeforeRet_;
	}
	result = hasKey__pureZjson_u3028((&(*node_p0)._kind_6.fields), key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u324)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** dest_p0, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* src_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!src_p1) goto LA3_;
		nimIncRef(src_p1);
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastDyn((*dest_p0));
		if (!T7_) goto LA8_;
		eqdestroy___pureZjson_u67((&(*(*dest_p0))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA8_: ;
	(*dest_p0) = src_p1;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getStr__pureZjson_u551)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* n_p0, NimStringV2 default_p1) {
	NimStringV2 result;
	nimfr_("getStr", "/usr/lib/nim/lib/pure/json.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimln_(255);	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (n_p0 == 0);
		if (T3_) goto LA4_;
		T3_ = !(((*n_p0).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimlf_(1715, "/usr/lib/nim/lib/system.nim");		eqcopy___system_u2772((&result), default_p1);
		goto BeforeRet_;
	}
	goto LA1_;
LA5_: ;
	{
		nimlf_(256, "/usr/lib/nim/lib/pure/json.nim");		nimlf_(1715, "/usr/lib/nim/lib/system.nim");		if (!(((16 &((NU8)1<<((NU)(((*n_p0).kind))&7U)))!=0))) 		{ raiseFieldErrorStr(TM__9b9bytt1stv9cZ8uqII7HFgew_28, dollar___pureZjson_u20((*n_p0).kind)); goto BeforeRet_;
		}
		eqcopy___system_u2772((&result), (*n_p0)._kind_1.str);
		goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1) {
	NIM_BOOL result;
	result = ((*((tyObject_NimRawSeq__9cILcSEMTM25Wr2S8osw5Bw*) (x_p0))).p == (*((tyObject_NimRawSeq__9cILcSEMTM25Wr2S8osw5Bw*) (y_p1))).p);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u257)(tySequence__jKinQKK5sMW4kMIzl4PsKQ* dest_p0, tySequence__jKinQKK5sMW4kMIzl4PsKQ src_p1) {
	NI T6_;
	NI colontmp_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__pureZjson_u276((&(*dest_p0)), T6_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T9_;
			T9_ = (*dest_p0).len;
			if (!(colontmp_ < T9_)) goto LA8;
			{
				if (!src_p1.p->data[colontmp_]) goto LA12_;
				nimIncRef(src_p1.p->data[colontmp_]);
			}
LA12_: ;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = nimDecRefIsLastDyn((*dest_p0).p->data[colontmp_]);
				if (!T16_) goto LA17_;
				eqdestroy___pureZjson_u67((&(*(*dest_p0).p->data[colontmp_])));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimRawDispose((*dest_p0).p->data[colontmp_], ((NI)8));
			}
LA17_: ;
			(*dest_p0).p->data[colontmp_] = src_p1.p->data[colontmp_];
			colontmp_ += ((NI)1);
		} LA8: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJString__pureZjson_u42)(NimStringV2 s_p0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	NimStringV2 colontmpD_;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
	nimfr_("newJString", "/usr/lib/nim/lib/pure/json.nim");
	nimlf_(218, "/usr/lib/nim/lib/pure/json.nim");	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4);
	nimlf_(1715, "/usr/lib/nim/lib/system.nim");	colontmpD_ = eqdup___system_u2775(s_p0);
	(*T1_)._kind_1.str = colontmpD_;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJInt__pureZjson_u429)(NI64 n_p0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
	nimfr_("newJInt", "/usr/lib/nim/lib/pure/json.nim");
	nimlf_(229, "/usr/lib/nim/lib/pure/json.nim");	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)2);
	(*T1_)._kind_2.num = n_p0;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJFloat__pureZjson_u432)(NF n_p0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
	nimfr_("newJFloat", "/usr/lib/nim/lib/pure/json.nim");
	nimln_(233);	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)3);
	(*T1_)._kind_3.fnum = n_p0;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJBool__pureZjson_u435)(NIM_BOOL b_p0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
	nimfr_("newJBool", "/usr/lib/nim/lib/pure/json.nim");
	nimln_(237);	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)1);
	(*T1_)._kind_4.bval = b_p0;
	result = T1_;
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NI, len__pureZjson_u2618)(tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw* t_p0) {
	NI result;
	nimfr_("len", "/usr/lib/nim/lib/pure/collections/tables.nim");
	nimlf_(1610, "/usr/lib/nim/lib/pure/collections/tables.nim");	result = (*t_p0).counter;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0) {
	NIM_BOOL result;
	nimfr_("isFilled", "/usr/lib/nim/lib/pure/collections/hashcommon.nim");
	nimlf_(27, "/usr/lib/nim/lib/pure/collections/hashcommon.nim");	result = !((hcode_p0 == ((NI)0)));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, copy__pureZjson_u4783)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* p_p0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
NIM_BOOL* nimErr_;
	nimfr_("copy", "/usr/lib/nim/lib/pure/json.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimlf_(641, "/usr/lib/nim/lib/pure/json.nim");	switch ((*p_p0).kind) {
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4):
	{
		nimln_(643);		if (!(((16 &((NU8)1<<((NU)(((*p_p0).kind))&7U)))!=0))) 		{ raiseFieldErrorStr(TM__9b9bytt1stv9cZ8uqII7HFgew_29, dollar___pureZjson_u20((*p_p0).kind)); goto BeforeRet_;
		}
		result = newJString__pureZjson_u42((*p_p0)._kind_1.str);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(644);		(*result).isUnquoted = (*p_p0).isUnquoted;
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)2):
	{
		nimln_(646);		if (!(((4 &((NU8)1<<((NU)(((*p_p0).kind))&7U)))!=0))) 		{ raiseFieldErrorStr(TM__9b9bytt1stv9cZ8uqII7HFgew_31, dollar___pureZjson_u20((*p_p0).kind)); goto BeforeRet_;
		}
		result = newJInt__pureZjson_u429((*p_p0)._kind_2.num);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)3):
	{
		nimln_(648);		if (!(((8 &((NU8)1<<((NU)(((*p_p0).kind))&7U)))!=0))) 		{ raiseFieldErrorStr(TM__9b9bytt1stv9cZ8uqII7HFgew_33, dollar___pureZjson_u20((*p_p0).kind)); goto BeforeRet_;
		}
		result = newJFloat__pureZjson_u432((*p_p0)._kind_3.fnum);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)1):
	{
		nimln_(650);		if (!(((2 &((NU8)1<<((NU)(((*p_p0).kind))&7U)))!=0))) 		{ raiseFieldErrorStr(TM__9b9bytt1stv9cZ8uqII7HFgew_35, dollar___pureZjson_u20((*p_p0).kind)); goto BeforeRet_;
		}
		result = newJBool__pureZjson_u435((*p_p0)._kind_4.bval);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)0):
	{
		nimln_(652);		result = newJNull__pureZjson_u438();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)5):
	{
		nimln_(654);		result = newJObject__pureZjson_u440();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			NimStringV2 key_1;
			tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* val_1;
			tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw colontmp_;
			NI L_1;
			key_1.len = 0; key_1.p = NIM_NIL;
			val_1 = NIM_NIL;
			nimZeroMem((void*)(&colontmp_), sizeof(tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw));
			nimlf_(1411, "/usr/lib/nim/lib/pure/collections/tables.nim");			if (!(((32 &((NU8)1<<((NU)(((*p_p0).kind))&7U)))!=0))) 			{ raiseFieldErrorStr(TM__9b9bytt1stv9cZ8uqII7HFgew_36, dollar___pureZjson_u20((*p_p0).kind)); goto BeforeRet_;
			}
			eqcopy___pureZjson_u486((&colontmp_), (&(*p_p0)._kind_6.fields));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(1819);			L_1 = len__pureZjson_u2618((&colontmp_));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(1820);			{
				NI h_1;
				nimln_(1387);				if (!(((NI)0) < colontmp_.counter)) goto LA10_;
				nimln_(1388);				h_1 = colontmp_.first;
				{
					nimln_(1389);					while (1) {
						NI nxt_1;
						if (!(((NI)0) <= h_1)) goto LA13;
						nimln_(1390);						if (h_1 < 0 || h_1 >= colontmp_.data.len){ raiseIndexError2(h_1,colontmp_.data.len-1); goto BeforeRet_;
						}
						nxt_1 = colontmp_.data.p->data[h_1].Field1;
						nimln_(1391);						{
							NIM_BOOL T16_;
							tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T19_;
							if (h_1 < 0 || h_1 >= colontmp_.data.len){ raiseIndexError2(h_1,colontmp_.data.len-1); goto BeforeRet_;
							}
							T16_ = (NIM_BOOL)0;
							T16_ = isFilled__pureZcollectionsZtables_u31(colontmp_.data.p->data[h_1].Field0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!T16_) goto LA17_;
							nimlf_(1715, "/usr/lib/nim/lib/system.nim");							if (h_1 < 0 || h_1 >= colontmp_.data.len){ raiseIndexError2(h_1,colontmp_.data.len-1); goto BeforeRet_;
							}
							eqcopy___system_u2772((&key_1), colontmp_.data.p->data[h_1].Field2);
							nimln_(934);							if (h_1 < 0 || h_1 >= colontmp_.data.len){ raiseIndexError2(h_1,colontmp_.data.len-1); goto BeforeRet_;
							}
							eqcopy___pureZjson_u324(&val_1, colontmp_.data.p->data[h_1].Field3);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							nimlf_(656, "/usr/lib/nim/lib/pure/json.nim");							if (!(((32 &((NU8)1<<((NU)(((*result).kind))&7U)))!=0))) 							{ raiseFieldErrorStr(TM__9b9bytt1stv9cZ8uqII7HFgew_37, dollar___pureZjson_u20((*result).kind)); goto BeforeRet_;
							}
							T19_ = NIM_NIL;
							T19_ = copy__pureZjson_u4783(val_1);
							if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u321(T19_); goto BeforeRet_;}
							X5BX5Deq___pureZjson_u740((&(*result)._kind_6.fields), key_1, T19_);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							nimlf_(1822, "/usr/lib/nim/lib/pure/collections/tables.nim");							{
								NI T22_;
								T22_ = (NI)0;
								T22_ = len__pureZjson_u2618((&colontmp_));
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								if (!!((T22_ == L_1))) goto LA23_;
								failedAssertImpl__stdZassertions_u95(TM__9b9bytt1stv9cZ8uqII7HFgew_39);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							}
LA23_: ;
						}
LA17_: ;
						nimln_(1393);						h_1 = nxt_1;
					} LA13: ;
				}
			}
LA10_: ;
			nimln_(1411);			eqdestroy___pureZjson_u483((&colontmp_));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimlf_(934, "/usr/lib/nim/lib/system.nim");			eqdestroy___pureZjson_u321(val_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(394);			if (key_1.p && !(key_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(key_1.p);
}
		}
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)6):
	{
		nimlf_(658, "/usr/lib/nim/lib/pure/json.nim");		result = newJArray__pureZjson_u503();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			tySequence__jKinQKK5sMW4kMIzl4PsKQ colontmp__2;
			tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** i_1;
			NI i_2;
			NI L_2;
			NI T27_;
			colontmp__2.len = 0; colontmp__2.p = NIM_NIL;
			i_1 = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg**)0;
			nimln_(218);			if (!(((64 &((NU8)1<<((NU)(((*p_p0).kind))&7U)))!=0))) 			{ raiseFieldErrorStr(TM__9b9bytt1stv9cZ8uqII7HFgew_40, dollar___pureZjson_u20((*p_p0).kind)); goto BeforeRet_;
			}
			eqcopy___pureZjson_u257((&colontmp__2), (*p_p0)._kind_7.elems);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimlf_(249, "/usr/lib/nim/lib/system/iterators.nim");			i_2 = ((NI)0);
			nimln_(250);			T27_ = colontmp__2.len;
			L_2 = T27_;
			{
				nimln_(251);				while (1) {
					tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T30_;
					if (!(i_2 < L_2)) goto LA29;
					nimlf_(659, "/usr/lib/nim/lib/pure/json.nim");					if (i_2 < 0 || i_2 >= colontmp__2.len){ raiseIndexError2(i_2,colontmp__2.len-1); goto BeforeRet_;
					}
					i_1 = &colontmp__2.p->data[i_2];
					nimln_(660);					if (!(((64 &((NU8)1<<((NU)(((*result).kind))&7U)))!=0))) 					{ raiseFieldErrorStr(TM__9b9bytt1stv9cZ8uqII7HFgew_41, dollar___pureZjson_u20((*result).kind)); goto BeforeRet_;
					}
					T30_ = NIM_NIL;
					T30_ = copy__pureZjson_u4783((*i_1));
					if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u321(T30_); goto BeforeRet_;}
					add__pureZjson_u671((&(*result)._kind_7.elems), T30_);
					nimlf_(13, "/usr/lib/nim/lib/system/iterators.nim");					i_2 += ((NI)1);
					nimln_(254);					{
						NI T33_;
						T33_ = colontmp__2.len;
						if (!!((T33_ == L_2))) goto LA34_;
						failedAssertImpl__stdZassertions_u95(TM__9b9bytt1stv9cZ8uqII7HFgew_43);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA34_: ;
				} LA29: ;
			}
			nimlf_(218, "/usr/lib/nim/lib/pure/json.nim");			eqdestroy___pureZjson_u254(colontmp__2);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
