/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/usr/lib/nim/lib -I/home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751 -o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@pnativesockets.nim.c.o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@pnativesockets.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
N_LIB_PRIVATE NIM_CONST int osInvalidSocket__pureZnativesockets_u48 = ((int)-1);
N_LIB_PRIVATE NIM_CONST int nativeAfInet__pureZnativesockets_u49 = ((int)2);
N_LIB_PRIVATE NIM_CONST int nativeAfInet6__pureZnativesockets_u50 = ((int)10);
N_LIB_PRIVATE NIM_CONST int nativeAfUnix__pureZnativesockets_u51 = ((int)1);
