/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/usr/lib/nim/lib -I/home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751 -o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@pnimpy.nim.c.o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@pnimpy.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_PyModuleDesc__50irLPVHYKKybdU9aIFHCRQ tyObject_PyModuleDesc__50irLPVHYKKybdU9aIFHCRQ;
N_LIB_PRIVATE tyObject_PyModuleDesc__50irLPVHYKKybdU9aIFHCRQ* curModuleDef__pkgZnimpy_u75;
N_LIB_PRIVATE NIM_THREADVAR NIM_BOOL gcInited__pkgZnimpy_u733;
