/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/usr/lib/nim/lib -I/home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751 -o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@pnimpy@spy_lib.nim.c.o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@pnimpy@spy_lib.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__0DSirJqYwP84JHfzAV1spQ tySequence__0DSirJqYwP84JHfzAV1spQ;
typedef struct tySequence__0DSirJqYwP84JHfzAV1spQ_Content tySequence__0DSirJqYwP84JHfzAV1spQ_Content;
typedef struct tyObject_PyLibcolonObjectType___v48fJCEB8qxiTsifTZmGJw tyObject_PyLibcolonObjectType___v48fJCEB8qxiTsifTZmGJw;
typedef struct tyObject_ExportedModule__aTfC2YZiDl69a8CTPw59cgiA tyObject_ExportedModule__aTfC2YZiDl69a8CTPw59cgiA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct tySequence__0DSirJqYwP84JHfzAV1spQ {
  NI len; tySequence__0DSirJqYwP84JHfzAV1spQ_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_ExportedModule__aTfC2YZiDl69a8CTPw59cgiA {
	NimStringV2 name;
	void* initAddr2;
	void* initAddr3;
};
struct tySequence__0DSirJqYwP84JHfzAV1spQ_Content { NI cap; tyObject_ExportedModule__aTfC2YZiDl69a8CTPw59cgiA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE tySequence__0DSirJqYwP84JHfzAV1spQ exportedModules__pkgZnimpyZpy95lib_u289;
N_LIB_PRIVATE NU pyObjectStartOffset__pkgZnimpyZpy95lib_u278;
N_LIB_PRIVATE tyObject_PyLibcolonObjectType___v48fJCEB8qxiTsifTZmGJw* pyLib__pkgZnimpyZpy95lib_u279;
N_LIB_PRIVATE NIM_THREADVAR NIM_BOOL pyThreadFrameInited__pkgZnimpyZpy95lib_u280;
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZnimpyZpy95lib_u1719)(tySequence__0DSirJqYwP84JHfzAV1spQ dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].name.p && !(dest_p0.p->data[colontmp_].name.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].name.p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_ExportedModule__aTfC2YZiDl69a8CTPw59cgiA));
}
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, atpnimpyatspy_libdotnim_Init000)(void) {
{
	nimfr_("py_lib", "/home/icarogdo/.nimble/pkgs2/nimpy-0.2.1-22173fb24ce9ca9d1c1db63fe15bdfb14e69c76a/nimpy/py_lib.nim");
	nimlf_(142, "/home/icarogdo/.nimble/pkgs2/nimpy-0.2.1-22173fb24ce9ca9d1c1db63fe15bdfb14e69c76a/nimpy/py_lib.nim");	exportedModules__pkgZnimpyZpy95lib_u289.len = 0; exportedModules__pkgZnimpyZpy95lib_u289.p = (tySequence__0DSirJqYwP84JHfzAV1spQ_Content*) newSeqPayload(0, sizeof(tyObject_ExportedModule__aTfC2YZiDl69a8CTPw59cgiA), NIM_ALIGNOF(tyObject_ExportedModule__aTfC2YZiDl69a8CTPw59cgiA));
	nimTestErrorFlag();
	popFrame();
}
}

