/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/usr/lib/nim/lib -I/home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751 -o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@prandom.nim.c.o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@prandom.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_Rand__pIYIFFBSminRbOe4kklEwA tyObject_Rand__pIYIFFBSminRbOe4kklEwA;
struct tyObject_Rand__pIYIFFBSminRbOe4kklEwA {
	NU64 a0;
	NU64 a1;
};
typedef long tyArray__7QgzEjDMuQ7wLEmz8Xm47g[5];
typedef int tyArray__wOqUtny8tUXASyN39bK1tGA[1];
static N_INLINE(void, initLock__coreZlocks_u7)(pthread_mutex_t* lock_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE NIM_CONST tyObject_Rand__pIYIFFBSminRbOe4kklEwA DefaultRandSeed__pureZrandom_u14 = {7616934476015405061ULL, 15122295919272093642ULL}
;
N_LIB_PRIVATE tyObject_Rand__pIYIFFBSminRbOe4kklEwA state__pureZrandom_u15;
N_LIB_PRIVATE pthread_mutex_t baseSeedLock__pureZrandom_u313;
N_LIB_PRIVATE tyObject_Rand__pIYIFFBSminRbOe4kklEwA baseState__pureZrandom_u314;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
static N_INLINE(void, initLock__coreZlocks_u7)(pthread_mutex_t* lock_p0) {
	pthread_mutex_init(lock_p0, ((pthread_mutexattr_t*) NIM_NIL));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, atprandomdotnim_Init000)(void) {
{
NIM_BOOL* nimErr_;
	nimfr_("random", "/usr/lib/nim/lib/pure/random.nim");
nimErr_ = nimErrorFlag();
	nimlf_(116, "/usr/lib/nim/lib/pure/random.nim");	state__pureZrandom_u15 = DefaultRandSeed__pureZrandom_u14;
	nimln_(682);	initLock__coreZlocks_u7((&baseSeedLock__pureZrandom_u313));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

