/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/usr/lib/nim/lib -I/home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751 -o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@pstd@sassertions.nim.c.o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@pstd@sassertions.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_AssertionDefect__5NaWWiRQbiFVJRYW9aFXCOA tyObject_AssertionDefect__5NaWWiRQbiFVJRYW9aFXCOA;
typedef struct tyObject_Defect__bs0znt1OsCtQtCP6xcUHbg tyObject_Defect__bs0znt1OsCtQtCP6xcUHbg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content;
typedef struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ {
  NI len; tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ trace;
	Exception* up;
};
struct tyObject_Defect__bs0znt1OsCtQtCP6xcUHbg {
	Exception Sup;
};
struct tyObject_AssertionDefect__5NaWWiRQbiFVJRYW9aFXCOA {
	tyObject_Defect__bs0znt1OsCtQtCP6xcUHbg Sup;
};
struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content { NI cap; tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert__stdZassertions_u28)(NimStringV2 msg_p0);
static N_INLINE(void, sysFatal__stdZassertions_u30)(NimStringV2 message_p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2775)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
extern TNimTypeV2 NTIv2__5NaWWiRQbiFVJRYW9aFXCOA_;
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
static N_INLINE(void, sysFatal__stdZassertions_u30)(NimStringV2 message_p1) {
	NimStringV2 colontmpD_;
	tyObject_AssertionDefect__5NaWWiRQbiFVJRYW9aFXCOA* T1_;
	nimfr_("sysFatal", "/usr/lib/nim/lib/system/fatal.nim");
{	T1_ = NIM_NIL;
	T1_ = (tyObject_AssertionDefect__5NaWWiRQbiFVJRYW9aFXCOA*) nimNewObj(sizeof(tyObject_AssertionDefect__5NaWWiRQbiFVJRYW9aFXCOA), NIM_ALIGNOF(tyObject_AssertionDefect__5NaWWiRQbiFVJRYW9aFXCOA));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIv2__5NaWWiRQbiFVJRYW9aFXCOA_);
	(*T1_).Sup.Sup.name = "AssertionDefect";
	nimlf_(62, "/usr/lib/nim/lib/system/fatal.nim");	nimlf_(1715, "/usr/lib/nim/lib/system.nim");	colontmpD_ = eqdup___system_u2775(message_p1);
	(*T1_).Sup.Sup.message = colontmpD_;
	nimlf_(62, "/usr/lib/nim/lib/system/fatal.nim");	raiseExceptionEx((Exception*)T1_, "AssertionDefect", "sysFatal", "/usr/lib/nim/lib/system/fatal.nim", 62);
goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert__stdZassertions_u28)(NimStringV2 msg_p0) {
NIM_BOOL* nimErr_;
	nimfr_("raiseAssert", "/usr/lib/nim/lib/std/assertions.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(40, "/usr/lib/nim/lib/std/assertions.nim");	sysFatal__stdZassertions_u30(msg_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0) {
NIM_BOOL* nimErr_;
	nimfr_("failedAssertImpl", "/usr/lib/nim/lib/std/assertions.nim");
{nimErr_ = nimErrorFlag();
	nimln_(45);	raiseAssert__stdZassertions_u28(msg_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
