/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/usr/lib/nim/lib -I/home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751 -o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@pstrutils.nim.c.o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@pstrutils.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef NI tyArray__9cc9aPiDa8VaWjVcFLabEDZQ[256];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9181)(NimStringV2 s_p0, NI first_p1, NI last_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2778)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2769)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2511)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStrA)(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_p0, NimStringV2 s_p1, NimStringV2 sub_p2, NI start_p3, NI last_p4);
N_LIB_PRIVATE N_NIMCALL(void, nsuInitNewSkipTable)(NimStringV2 sub_p0, tyArray__9cc9aPiDa8VaWjVcFLabEDZQ Result);
N_LIB_PRIVATE N_NIMCALL(void, nsuInitSkipTable)(NI* a_p0, NimStringV2 sub_p1);
N_LIB_PRIVATE N_NIMCALL(void, fill__pureZstrutils_u1634)(NI* a_p0, NI a_p0Len_0, NI value_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_10 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_11 = {0, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_10};
static const struct {
  NI cap; NIM_CHAR data[72+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_12 = { 72 | NIM_STRLIT_FLAG, "/usr/lib/nim/lib/pure/strutils.nim(406, 9) `not (\'\\x00\' in Whitespace)` " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_13 = {72, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_12};
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuStrip)(NimStringV2 s_p0, NIM_BOOL leading_p1, NIM_BOOL trailing_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p3) {
	NimStringV2 result;
	NI first_1;
	NI last_1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_2;
	nimfr_("strip", "/usr/lib/nim/lib/pure/strutils.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(2996, "/usr/lib/nim/lib/pure/strutils.nim");	first_1 = ((NI)0);
	nimln_(2997);	if (nimSubInt(s_p0.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_2)) { raiseOverflow(); goto BeforeRet_;
	};
	last_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_2);
	nimln_(2998);	{
		if (!leading_p1) goto LA3_;
		{
			nimln_(2999);			while (1) {
				NIM_BOOL T7_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_3;
				T7_ = (NIM_BOOL)0;
				T7_ = (first_1 <= last_1);
				if (!(T7_)) goto LA8_;
				if (first_1 < 0 || first_1 >= s_p0.len){ raiseIndexError2(first_1,s_p0.len-1); goto BeforeRet_;
				}
				T7_ = ((chars_p3[(NU)((((NU8)(s_p0.p->data[first_1]))))>>3] &(1U<<((NU)((((NU8)(s_p0.p->data[first_1]))))&7U)))!=0);
LA8_: ;
				if (!T7_) goto LA6;
				if (nimAddInt(first_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_3)) { raiseOverflow(); goto BeforeRet_;
				};
				first_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_3);
			} LA6: ;
		}
	}
LA3_: ;
	nimln_(3000);	{
		if (!trailing_p2) goto LA11_;
		{
			nimln_(3001);			while (1) {
				NIM_BOOL T15_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_4;
				T15_ = (NIM_BOOL)0;
				T15_ = (first_1 <= last_1);
				if (!(T15_)) goto LA16_;
				if (last_1 < 0 || last_1 >= s_p0.len){ raiseIndexError2(last_1,s_p0.len-1); goto BeforeRet_;
				}
				T15_ = ((chars_p3[(NU)((((NU8)(s_p0.p->data[last_1]))))>>3] &(1U<<((NU)((((NU8)(s_p0.p->data[last_1]))))&7U)))!=0);
LA16_: ;
				if (!T15_) goto LA14;
				if (nimSubInt(last_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_4)) { raiseOverflow(); goto BeforeRet_;
				};
				last_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4);
			} LA14: ;
		}
	}
LA11_: ;
	nimln_(3002);	result = substr__system_u9181(s_p0, first_1, last_1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuJoinSep)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 sep_p1) {
	NimStringV2 result;
	nimfr_("join", "/usr/lib/nim/lib/pure/strutils.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimln_(1871);	{
		NI L_1;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_5;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_6;
		if (!(((NI)0) < a_p0Len_0)) goto LA3_;
		nimln_(1872);		if (nimSubInt(a_p0Len_0, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_5)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimMulInt(sep_p1.len, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_5), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_6)) { raiseOverflow(); goto BeforeRet_;
		};
		L_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_6);
		{
			NI i_1;
			NI colontmp_;
			NI res_1;
			i_1 = (NI)0;
			colontmp_ = (NI)0;
			nimlf_(81, "/usr/lib/nim/lib/system/iterators_1.nim");			nimlf_(1873, "/usr/lib/nim/lib/pure/strutils.nim");			colontmp_ = (a_p0Len_0-1);
			nimlf_(96, "/usr/lib/nim/lib/system/iterators_1.nim");			res_1 = ((NI)0);
			{
				nimln_(97);				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_7;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_8;
					if (!(res_1 <= colontmp_)) goto LA7;
					nimlf_(1873, "/usr/lib/nim/lib/pure/strutils.nim");					i_1 = ((NI) (res_1));
					if (i_1 < 0 || i_1 >= a_p0Len_0){ raiseIndexError2(i_1,a_p0Len_0-1); goto BeforeRet_;
					}
					if (nimAddInt(L_1, a_p0[i_1].len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_7)) { raiseOverflow(); goto BeforeRet_;
					};
					L_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_7);
					nimlf_(102, "/usr/lib/nim/lib/system/iterators_1.nim");					if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_8)) { raiseOverflow(); goto BeforeRet_;
					};
					res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_8);
				} LA7: ;
			}
		}
		nimlf_(1874, "/usr/lib/nim/lib/pure/strutils.nim");		if ((L_1) < ((NI)0) || (L_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(L_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		result = rawNewString((L_1));
		nimln_(1875);		if (((NI)0) < 0 || ((NI)0) >= a_p0Len_0){ raiseIndexError2(((NI)0),a_p0Len_0-1); goto BeforeRet_;
		}
		prepareAdd((&result), a_p0[((NI)0)].len + 0);
appendString((&result), a_p0[((NI)0)]);
		{
			NI i_2;
			NI colontmp__2;
			NI res_2;
			i_2 = (NI)0;
			colontmp__2 = (NI)0;
			nimlf_(81, "/usr/lib/nim/lib/system/iterators_1.nim");			nimlf_(1876, "/usr/lib/nim/lib/pure/strutils.nim");			colontmp__2 = (a_p0Len_0-1);
			nimlf_(96, "/usr/lib/nim/lib/system/iterators_1.nim");			res_2 = ((NI)1);
			{
				nimln_(97);				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_9;
					if (!(res_2 <= colontmp__2)) goto LA10;
					nimlf_(1876, "/usr/lib/nim/lib/pure/strutils.nim");					i_2 = ((NI) (res_2));
					nimln_(1877);					prepareAdd((&result), sep_p1.len + 0);
appendString((&result), sep_p1);
					nimln_(1878);					if (i_2 < 0 || i_2 >= a_p0Len_0){ raiseIndexError2(i_2,a_p0Len_0-1); goto BeforeRet_;
					}
					prepareAdd((&result), a_p0[i_2].len + 0);
appendString((&result), a_p0[i_2]);
					nimlf_(102, "/usr/lib/nim/lib/system/iterators_1.nim");					if (nimAddInt(res_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_9)) { raiseOverflow(); goto BeforeRet_;
					};
					res_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_9);
				} LA10: ;
			}
		}
	}
	goto LA1_;
LA3_: ;
	{
		nimlf_(1880, "/usr/lib/nim/lib/pure/strutils.nim");		result = TM__JGc9b9bh2D3nTdUR7TGyq8aA_11;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitWhitespace)(NimStringV2 s_p0, NI maxsplit_p1) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
NIM_BOOL* nimErr_;
	nimfr_("splitWhitespace", "/usr/lib/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimln_(418);	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		NimStringV2 xX60gensym74__1;
		NI lastX60gensym59__1;
		NI splitsX60gensym59__1;
		xX60gensym74__1.len = 0; xX60gensym74__1.p = NIM_NIL;
		nimln_(404);		lastX60gensym59__1 = ((NI)0);
		nimln_(405);		splitsX60gensym59__1 = maxsplit_p1;
		nimln_(406);		{
			if (!NIM_FALSE) goto LA5_;
			failedAssertImpl__stdZassertions_u95(TM__JGc9b9bh2D3nTdUR7TGyq8aA_13);
			if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
		}
LA5_: ;
		{
			nimln_(743);			while (1) {
				NI firstX60gensym59__1;
				nimln_(407);				if (!(lastX60gensym59__1 < s_p0.len)) goto LA8;
				{
					nimln_(408);					while (1) {
						NIM_BOOL T11_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_14;
						T11_ = (NIM_BOOL)0;
						T11_ = (lastX60gensym59__1 < s_p0.len);
						if (!(T11_)) goto LA12_;
						if (lastX60gensym59__1 < 0 || lastX60gensym59__1 >= s_p0.len){ raiseIndexError2(lastX60gensym59__1,s_p0.len-1); goto LA2_;
						}
						T11_ = (((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(32)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(9)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(11)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(13)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(10)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(12)));
LA12_: ;
						if (!T11_) goto LA10;
						if (nimAddInt(lastX60gensym59__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_14)) { raiseOverflow(); goto LA2_;
						};
						lastX60gensym59__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_14);
					} LA10: ;
				}
				nimln_(409);				firstX60gensym59__1 = lastX60gensym59__1;
				{
					nimln_(410);					while (1) {
						NIM_BOOL T15_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_15;
						T15_ = (NIM_BOOL)0;
						T15_ = (lastX60gensym59__1 < s_p0.len);
						if (!(T15_)) goto LA16_;
						if (lastX60gensym59__1 < 0 || lastX60gensym59__1 >= s_p0.len){ raiseIndexError2(lastX60gensym59__1,s_p0.len-1); goto LA2_;
						}
						T15_ = !((((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(32)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(9)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(11)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(13)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(10)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(12))));
LA16_: ;
						if (!T15_) goto LA14;
						if (nimAddInt(lastX60gensym59__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_15)) { raiseOverflow(); goto LA2_;
						};
						lastX60gensym59__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_15);
					} LA14: ;
				}
				nimln_(411);				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_16;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_17;
					NimStringV2 T25_;
					NimStringV2 blitTmp_1;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_18;
					if (nimSubInt(lastX60gensym59__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_16)) { raiseOverflow(); goto LA2_;
					};
					if (!(firstX60gensym59__1 <= (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_16))) goto LA19_;
					nimln_(412);					{
						if (!(splitsX60gensym59__1 == ((NI)0))) goto LA23_;
						lastX60gensym59__1 = s_p0.len;
					}
LA23_: ;
					nimlf_(1715, "/usr/lib/nim/lib/system.nim");					nimlf_(929, "/usr/lib/nim/lib/pure/strutils.nim");					nimln_(413);					if (nimSubInt(lastX60gensym59__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_17)) { raiseOverflow(); goto LA2_;
					};
					nimln_(929);					T25_.len = 0; T25_.p = NIM_NIL;
					T25_ = substr__system_u9181(s_p0, firstX60gensym59__1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_17));
					nimlf_(1715, "/usr/lib/nim/lib/system.nim");					eqsink___system_u2778((&xX60gensym74__1), T25_);
					nimlf_(419, "/usr/lib/nim/lib/pure/strutils.nim");					blitTmp_1 = xX60gensym74__1;
					nimlf_(1715, "/usr/lib/nim/lib/system.nim");					eqwasMoved___system_u2769((&xX60gensym74__1));
					nimlf_(419, "/usr/lib/nim/lib/pure/strutils.nim");					add__stdZenumutils_u70((&result), blitTmp_1);
					nimln_(414);					{
						if (!(splitsX60gensym59__1 == ((NI)0))) goto LA28_;
						goto LA7;
					}
LA28_: ;
					nimln_(415);					if (nimSubInt(splitsX60gensym59__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_18)) { raiseOverflow(); goto LA2_;
					};
					splitsX60gensym59__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_18);
				}
LA19_: ;
			} LA8: ;
		} LA7: ;
		{
			LA2_:;
		}
		{
			nimlf_(394, "/usr/lib/nim/lib/system.nim");			if (xX60gensym74__1.p && !(xX60gensym74__1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(xX60gensym74__1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2511(s_p0);
	}
LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c_p0) {
	NIM_CHAR result;
	nimfr_("toLowerAscii", "/usr/lib/nim/lib/pure/strutils.nim");
	nimlf_(218, "/usr/lib/nim/lib/pure/strutils.nim");	{
		if (!(((NU8)(c_p0)) >= ((NU8)(65)) && ((NU8)(c_p0)) <= ((NU8)(90)))) goto LA3_;
		nimln_(219);		result = ((NIM_CHAR) ((NU8)(((NU8) (((NU8)(c_p0)))) ^ ((NU8)32))));
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(221);		result = c_p0;
	}
LA1_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToLowerAsciiStr)(NimStringV2 s_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("toLowerAscii", "/usr/lib/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(224);	if ((s_p0.len) < ((NI)0) || (s_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((s_p0.len));
	{
		NI iX60gensym7__1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_19;
		NI res_1;
		iX60gensym7__1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "/usr/lib/nim/lib/system/iterators_1.nim");		nimlf_(225, "/usr/lib/nim/lib/pure/strutils.nim");		if (nimSubInt(s_p0.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_19)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_19);
		nimlf_(96, "/usr/lib/nim/lib/system/iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(97);			while (1) {
				NIM_CHAR T4_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_20;
				if (!(res_1 <= colontmp_)) goto LA3;
				nimlf_(239, "/usr/lib/nim/lib/pure/strutils.nim");				iX60gensym7__1 = ((NI) (res_1));
				nimln_(226);				if (iX60gensym7__1 < 0 || iX60gensym7__1 >= result.len){ raiseIndexError2(iX60gensym7__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (iX60gensym7__1 < 0 || iX60gensym7__1 >= s_p0.len){ raiseIndexError2(iX60gensym7__1,s_p0.len-1); goto BeforeRet_;
				}
				T4_ = (NIM_CHAR)0;
				T4_ = nsuToLowerAsciiChar(s_p0.p->data[iX60gensym7__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				result.p->data[iX60gensym7__1] = T4_;
				nimlf_(102, "/usr/lib/nim/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_20)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_20);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringV2 s_p0, NimStringV2 prefix_p1) {
	NIM_BOOL result;
	NI prefixLenX60gensym144__1;
	NI sLenX60gensym144__1;
	NI iX60gensym144__1;
	nimfr_("startsWith", "/usr/lib/nim/lib/pure/strutils.nim");
{	nimlf_(1647, "/usr/lib/nim/lib/pure/strutils.nim");	result = NIM_FALSE;
	nimlf_(56, "/usr/lib/nim/lib/std/private/strimpl.nim");	prefixLenX60gensym144__1 = prefix_p1.len;
	nimln_(57);	sLenX60gensym144__1 = s_p0.len;
	nimln_(58);	iX60gensym144__1 = ((NI)0);
	{
		nimlf_(1648, "/usr/lib/nim/lib/pure/strutils.nim");		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_21;
			nimlf_(60, "/usr/lib/nim/lib/std/private/strimpl.nim");			{
				if (!(prefixLenX60gensym144__1 <= iX60gensym144__1)) goto LA5_;
				nimlf_(1634, "/usr/lib/nim/lib/pure/strutils.nim");				nimlf_(60, "/usr/lib/nim/lib/std/private/strimpl.nim");				result = NIM_TRUE;
				goto BeforeRet_;
			}
LA5_: ;
			nimln_(61);			{
				NIM_BOOL T9_;
				T9_ = (NIM_BOOL)0;
				T9_ = (sLenX60gensym144__1 <= iX60gensym144__1);
				if (T9_) goto LA10_;
				if (iX60gensym144__1 < 0 || iX60gensym144__1 >= s_p0.len){ raiseIndexError2(iX60gensym144__1,s_p0.len-1); goto BeforeRet_;
				}
				if (iX60gensym144__1 < 0 || iX60gensym144__1 >= prefix_p1.len){ raiseIndexError2(iX60gensym144__1,prefix_p1.len-1); goto BeforeRet_;
				}
				T9_ = !(((NU8)(s_p0.p->data[iX60gensym144__1]) == (NU8)(prefix_p1.p->data[iX60gensym144__1])));
LA10_: ;
				if (!T9_) goto LA11_;
				nimlf_(1634, "/usr/lib/nim/lib/pure/strutils.nim");				nimlf_(61, "/usr/lib/nim/lib/std/private/strimpl.nim");				result = NIM_FALSE;
				goto BeforeRet_;
			}
LA11_: ;
			nimln_(62);			if (nimAddInt(iX60gensym144__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_21)) { raiseOverflow(); goto BeforeRet_;
			};
			iX60gensym144__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_21);
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/usr/lib/nim/lib/system/arithmetics.nim");
	nimlf_(377, "/usr/lib/nim/lib/system/arithmetics.nim");	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
	NI length_1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_23;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_24;
	nimfr_("find", "/usr/lib/nim/lib/pure/strutils.nim");
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimlf_(1972, "/usr/lib/nim/lib/pure/strutils.nim");	result = ((NI)-1);
	nimln_(1973);	{
		if (!(last_p3 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p0.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p3;
		last_2 = colontmpD__2;
	}
LA1_: ;
	nimln_(1984);	if (nimSubInt(last_2, start_p2, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_23)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_23), ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_24)) { raiseOverflow(); goto BeforeRet_;
	};
	length_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_24);
	nimln_(1985);	{
		void* found_1;
		if (!(((NI)0) < length_1)) goto LA8_;
		nimln_(1986);		if (start_p2 < 0 || start_p2 >= s_p0.len){ raiseIndexError2(start_p2,s_p0.len-1); goto BeforeRet_;
		}
		found_1 = memchr(((void*) ((&s_p0.p->data[start_p2]))), ((int) (((NU8)(sub_p1)))), ((size_t) (length_1)));
		nimln_(1987);		{
			if (!!((found_1 == 0))) goto LA12_;
			nimln_(1988);			nimln_(1960);			nimln_(1988);			result = minuspercent___system_u813(((NI) (ptrdiff_t) (found_1)), ((NI) (nimToCStringConv(s_p0))));
			goto BeforeRet_;
		}
LA12_: ;
	}
LA8_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStrA)(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_p0, NimStringV2 s_p1, NimStringV2 sub_p2, NI start_p3, NI last_p4) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
	NI subLast_1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_26;
	NI skip_1;
	nimfr_("find", "/usr/lib/nim/lib/pure/strutils.nim");
{	result = (NI)0;
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimln_(1932);	{
		if (!(last_p4 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p1.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p4;
		last_2 = colontmpD__2;
	}
LA1_: ;
	nimln_(1933);	if (nimSubInt(sub_p2.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_26)) { raiseOverflow(); goto BeforeRet_;
	};
	subLast_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_26);
	nimln_(1935);	{
		if (!(subLast_1 == ((NI)-1))) goto LA8_;
		nimln_(1938);		nimln_(1920);		nimln_(1938);		result = start_p3;
		goto BeforeRet_;
	}
LA8_: ;
	nimln_(1942);	result = ((NI)-1);
	nimln_(1943);	skip_1 = start_p3;
	{
		nimln_(1945);		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_27;
			NI i_1;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_30;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_31;
			if (nimSubInt(last_2, skip_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_27)) { raiseOverflow(); goto BeforeRet_;
			};
			if (!(subLast_1 <= (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_27))) goto LA11;
			nimln_(1946);			i_1 = subLast_1;
			{
				nimln_(1947);				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_28;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_29;
					if (nimAddInt(skip_1, i_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_28)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28) >= s_p1.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28),s_p1.len-1); goto BeforeRet_;
					}
					if (i_1 < 0 || i_1 >= sub_p2.len){ raiseIndexError2(i_1,sub_p2.len-1); goto BeforeRet_;
					}
					if (!((NU8)(s_p1.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28)]) == (NU8)(sub_p2.p->data[i_1]))) goto LA13;
					nimln_(1948);					{
						if (!(i_1 == ((NI)0))) goto LA16_;
						nimln_(1949);						nimln_(1920);						nimln_(1949);						result = skip_1;
						goto BeforeRet_;
					}
LA16_: ;
					nimln_(1950);					if (nimSubInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_29)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_29);
				} LA13: ;
			}
			nimln_(1951);			if (nimAddInt(skip_1, subLast_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_30)) { raiseOverflow(); goto BeforeRet_;
			};
			if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_30) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_30) >= s_p1.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_30),s_p1.len-1); goto BeforeRet_;
			}
			if (nimAddInt(skip_1, a_p0[(((NU8)(s_p1.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_30)])))- 0], &TM__JGc9b9bh2D3nTdUR7TGyq8aA_31)) { raiseOverflow(); goto BeforeRet_;
			};
			if (TM__JGc9b9bh2D3nTdUR7TGyq8aA_31 < 0 || TM__JGc9b9bh2D3nTdUR7TGyq8aA_31 > IL64(9223372036854775807)){ raiseOverflow(); goto BeforeRet_;
			}
			skip_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_31);
		} LA11: ;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuInitSkipTable)(NI* a_p0, NimStringV2 sub_p1) {
	NI m_1;
NIM_BOOL* nimErr_;
	nimfr_("initSkipTable", "/usr/lib/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimln_(1905);	m_1 = sub_p1.len;
	nimln_(1906);	fill__pureZstrutils_u1634(a_p0, 256, m_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i_1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_32;
		NI i_2;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(126, "/usr/lib/nim/lib/system/iterators_1.nim");		nimlf_(1908, "/usr/lib/nim/lib/pure/strutils.nim");		if (nimSubInt(m_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_32)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32);
		nimlf_(128, "/usr/lib/nim/lib/system/iterators_1.nim");		i_2 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_33;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_34;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_35;
				if (!(i_2 < colontmp_)) goto LA3;
				nimlf_(1908, "/usr/lib/nim/lib/pure/strutils.nim");				i_1 = i_2;
				nimln_(1909);				if (i_1 < 0 || i_1 >= sub_p1.len){ raiseIndexError2(i_1,sub_p1.len-1); goto BeforeRet_;
				}
				if (nimSubInt(m_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_33)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_33), i_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_34)) { raiseOverflow(); goto BeforeRet_;
				};
				a_p0[(((NU8)(sub_p1.p->data[i_1])))- 0] = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_34);
				nimlf_(131, "/usr/lib/nim/lib/system/iterators_1.nim");				if (nimAddInt(i_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_35)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_35);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, nsuInitNewSkipTable)(NimStringV2 sub_p0, tyArray__9cc9aPiDa8VaWjVcFLabEDZQ Result) {
NIM_BOOL* nimErr_;
	nimfr_("initSkipTable", "/usr/lib/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(1918, "/usr/lib/nim/lib/pure/strutils.nim");	nsuInitSkipTable(Result, sub_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NI start_p2, NI last_p3) {
	NI result;
	NI subLen_1;
NIM_BOOL* nimErr_;
	nimfr_("find", "/usr/lib/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(2032);	{
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_22;
		if (nimSubInt(s_p0.len, start_p2, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_22)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_22) < sub_p1.len)) goto LA3_;
		nimln_(2020);		nimln_(2032);		result = ((NI)-1);
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(2033);	{
		if (!(sub_p1.len == ((NI)1))) goto LA7_;
		nimln_(2020);		nimln_(2033);		if (((NI)0) < 0 || ((NI)0) >= sub_p1.len){ raiseIndexError2(((NI)0),sub_p1.len-1); goto BeforeRet_;
		}
		result = nsuFindChar(s_p0, sub_p1.p->data[((NI)0)], start_p2, last_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA7_: ;
	nimln_(2042);	subLen_1 = sub_p1.len;
	nimln_(2043);	{
		NIM_BOOL T11_;
		NIM_BOOL T12_;
		void* found_1;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_25;
		NI T17_;
		T11_ = (NIM_BOOL)0;
		T12_ = (NIM_BOOL)0;
		T12_ = (last_p3 < ((NI)0));
		if (!(T12_)) goto LA13_;
		T12_ = (start_p2 < s_p0.len);
LA13_: ;
		T11_ = T12_;
		if (!(T11_)) goto LA14_;
		T11_ = !((subLen_1 == ((NI)0)));
LA14_: ;
		if (!T11_) goto LA15_;
		nimln_(2044);		if (start_p2 < 0 || start_p2 >= s_p0.len){ raiseIndexError2(start_p2,s_p0.len-1); goto BeforeRet_;
		}
		if (nimSubInt(s_p0.len, start_p2, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_25)) { raiseOverflow(); goto BeforeRet_;
		};
		found_1 = memmem(((void*) ((&s_p0.p->data[start_p2]))), ((size_t) ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_25))), ((void*) (nimToCStringConv(sub_p1))), ((size_t) (subLen_1)));
		T17_ = (NI)0;
		nimln_(2045);		{
			if (!!((found_1 == 0))) goto LA20_;
			nimln_(2046);			result = minuspercent___system_u813(((NI) (ptrdiff_t) (found_1)), ((NI) (nimToCStringConv(s_p0))));
		}
		goto LA18_;
LA20_: ;
		{
			nimln_(2045);			nimln_(2048);			result = ((NI)-1);
		}
LA18_: ;
	}
	goto LA9_;
LA15_: ;
	{
		tyArray__9cc9aPiDa8VaWjVcFLabEDZQ T24_;
		nimln_(2036);		nimZeroMem((void*)T24_, sizeof(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ));
		nsuInitNewSkipTable(sub_p1, T24_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = nsuFindStrA(T24_, s_p0, sub_p1, start_p2, last_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA9_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_u1900)(NimStringV2 s_p0, NimStringV2 sub_p1) {
	NIM_BOOL result;
	NI T1_;
NIM_BOOL* nimErr_;
	nimfr_("contains", "/usr/lib/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(2190);	nimln_(2185);	nimln_(2190);	T1_ = (NI)0;
	T1_ = nsuFindStr(s_p0, sub_p1, ((NI)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
