/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/usr/lib/nim/lib -I/home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751 -o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@ptimes.nim.c.o /home/icarogdo/dev/glaucoplastic/.glaucoplastic-tests/strict-memory-20260806-075751/nimcache/@ptimes.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_TimezonecolonObjectType___DA7QPQgnivWR9cVVp7gTo0A tyObject_TimezonecolonObjectType___DA7QPQgnivWR9cVVp7gTo0A;
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___DA7QPQgnivWR9cVVp7gTo0A* utcInstance__pureZtimes_u2055;
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___DA7QPQgnivWR9cVVp7gTo0A* localInstance__pureZtimes_u2056;
